"""The trainer-diag relay must not execute an issue body's PROSE.

BL-20260731-TRAINERDIAG-TRAILING-PROSE. The `cmd:` extractor stripped markdown
fence lines but never STOPPED at the closing one, so everything after the fenced
block — the explanatory paragraphs, the `---` rule, the attribution footer — was
handed to bash as commands. Observed live in trainer-diag issue #8157, whose own
output carried `Expected: command not found` after the real work had run.

Harmless that time. Not harmless in general: prose is untrusted-ish free text
that can contain backticks (command substitution), parentheses (a syntax error
that can abort the remainder), and redirects. A body that reads as documentation
must never execute as code.

These tests run the REAL awk program, extracted from the workflow YAML, rather
than a copy of it — a copy would let the workflow and its test drift apart,
which is the failure mode this repo's guards exist to catch.
"""
from __future__ import annotations

import re
import shutil
import subprocess
from pathlib import Path

import pytest

_WORKFLOW = (Path(__file__).resolve().parents[1]
             / ".github" / "workflows" / "trainer-vm-diag.yml")


def _awk_program() -> str:
    """Pull the extractor's awk source straight out of the workflow."""
    text = _WORKFLOW.read_text(encoding="utf-8")
    m = re.search(r"awk '\n(.*?)\n\s*' \)\"", text, re.DOTALL)
    assert m, "could not locate the awk program in trainer-vm-diag.yml"
    return m.group(1)


def _extract(body: str) -> str:
    awk = shutil.which("awk") or shutil.which("gawk") or shutil.which("mawk")
    if not awk:
        pytest.skip("awk not available")
    proc = subprocess.run([awk, _awk_program()], input=body,
                          capture_output=True, text=True, timeout=30)
    assert proc.returncode == 0, proc.stderr
    return proc.stdout


def test_trailing_prose_after_the_closing_fence_is_not_extracted():
    """The #8157 shape, verbatim in structure."""
    body = (
        "Applies the recovery, then verifies the write landed.\n"
        "\n"
        "```\n"
        "cmd:\n"
        "echo real-work\n"
        "```\n"
        "\n"
        "Expected from the dry run: **17 derived**, `vol_threshold_source` set.\n"
        "\n"
        "---\n"
        "_Generated by [Claude Code](https://claude.ai/code)_\n"
    )
    out = _extract(body)
    assert "echo real-work" in out
    assert "Expected from the dry run" not in out, (
        "trailing prose leaked into the command — this is the #8157 defect")
    assert "Generated by" not in out
    assert "---" not in out


def test_backticks_in_trailing_prose_never_reach_the_command():
    """Command substitution is the sharp edge, not the noise."""
    body = (
        "```\n"
        "cmd:\n"
        "echo safe\n"
        "```\n"
        "Note: `rm -rf /tmp/whatever` would be substituted if this leaked.\n"
    )
    out = _extract(body)
    assert "echo safe" in out
    assert "rm -rf" not in out


def test_cmd_that_opens_its_own_fence_still_works():
    """The other documented layout: `cmd:` first, fence second."""
    body = (
        "cmd:\n"
        "```bash\n"
        "echo one\n"
        "echo two\n"
        "```\n"
        "trailing prose here\n"
    )
    out = _extract(body)
    assert "echo one" in out and "echo two" in out
    assert "trailing prose" not in out
    assert "```" not in out


def test_unfenced_single_line_cmd_is_unchanged():
    body = "cmd: journalctl -u ict-trainer.service -n 100\n"
    assert _extract(body).strip() == "journalctl -u ict-trainer.service -n 100"


def test_unfenced_block_still_stops_at_the_next_top_level_key():
    """BL-20260607-002 behaviour must survive the fence change."""
    body = (
        "cmd: |\n"
        "  echo alpha\n"
        "  echo beta\n"
        "reason: |\n"
        "  some prose that must not run\n"
    )
    out = _extract(body)
    assert "echo alpha" in out and "echo beta" in out
    assert "some prose that must not run" not in out
    assert "reason:" not in out


def test_a_script_line_is_not_mistaken_for_a_top_level_key():
    """`echo x` and `python3 y` have no colon; a URL line does, mid-line."""
    body = (
        "```\n"
        "cmd:\n"
        "echo 'see https://example.com/x'\n"
        "python3 scripts/ml/thing.py --root out\n"
        "```\n"
    )
    out = _extract(body)
    assert "python3 scripts/ml/thing.py --root out" in out
    assert "example.com" in out


def test_a_fenced_script_line_starting_word_colon_is_not_a_top_level_key():
    """BL-20260830-TRAINERDIAG-FENCED-KEY-TRUNC.

    The sibling test above only covers script lines with NO colon at column 0
    (`echo x`, `python3 y`) and a URL whose colon is mid-line. Plenty of real
    code begins `word:` at column 0 — `try:` / `else:` / `except:` / `finally:`
    in an embedded python heredoc, a shell `case` label — and the YAML-key
    terminator fired on those, truncating the command mid-script.

    Observed live on trainer-diag #10452: an embedded `try:` cut the script at
    line 15, leaving an unterminated heredoc.
    """
    body = (
        "```\n"
        "cmd:\n"
        "echo before\n"
        "python3 - <<'PY'\n"
        "try:\n"
        "    import torch\n"
        "except Exception as e:\n"
        "    print(e)\n"
        "PY\n"
        "echo after\n"
        "```\n"
    )
    out = _extract(body)
    assert "echo before" in out
    assert "try:" in out, "the python heredoc was truncated at `try:`"
    assert "except Exception as e:" in out
    assert "echo after" in out, "everything after the heredoc was dropped"


def test_fenced_truncation_would_have_run_a_partial_script_silently():
    """The reason the bug is worse than it looks: the PREFIX STILL RUNS.

    #10452 errored only by luck — its cut landed mid-heredoc. A cut landing on
    a complete statement yields plausible output and exit 0 with the remainder
    silently gone, so a partial answer cannot be told from a complete one.
    """
    body = (
        "```\n"
        "cmd:\n"
        "echo REAL_WORK\n"
        "cat > /tmp/cfg.yaml <<'EOF'\n"
        "retention_days: 30\n"
        "EOF\n"
        "echo MUST_ALSO_RUN\n"
        "```\n"
    )
    out = _extract(body)
    assert "echo REAL_WORK" in out
    assert "retention_days: 30" in out
    assert "echo MUST_ALSO_RUN" in out, (
        "a heredoc-written YAML key truncated the block; the prefix would "
        "have run and returned exit 0 as if complete"
    )


def test_unfenced_block_still_stops_at_a_top_level_key_after_the_fix():
    """Regression guard: the !fence qualifier must not weaken the UNFENCED
    terminator, which is what BL-20260607-002 added."""
    body = (
        "cmd: |\n"
        "  echo work\n"
        "reason: this is prose and must never execute\n"
        "  echo never\n"
    )
    out = _extract(body)
    assert "echo work" in out
    assert "reason" not in out
    assert "echo never" not in out


def test_multiple_fenced_blocks_only_the_cmd_one_is_taken():
    body = (
        "```\n"
        "not the command\n"
        "```\n"
        "\n"
        "```\n"
        "cmd:\n"
        "echo chosen\n"
        "```\n"
        "\n"
        "```\n"
        "echo definitely not\n"
        "```\n"
    )
    out = _extract(body)
    assert "echo chosen" in out
    assert "not the command" not in out
    assert "echo definitely not" not in out


def test_unfenced_block_stops_at_trailing_prose_that_is_not_a_key():
    """The recurrence, observed live in trainer-diag issue #9400 (2026-08-15).

    The #8157 fix ends the block at a CLOSING FENCE, and BL-20260607-002 ends it
    at the next top-level `key:`. An unfenced ``cmd: |`` block whose trailing
    prose is neither — an ordinary sentence — matched no terminator and ran off
    the end into bash, exactly as #8157 did. #9400's own explanatory paragraph
    came back as ``Three: command not found`` / ``eth_denom_2h: command not
    found``.

    Two terminators covering two layouts read as complete until a third layout
    arrives. YAML itself gives the general rule for the ``|`` form: block-scalar
    content MUST be indented, so the first non-indented non-empty line ends it,
    whatever it looks like.
    """
    body = (
        "cmd: |\n"
        "  set -uo pipefail\n"
        "  echo hello\n"
        "\n"
        "Three questions in one pull, while the screen runs:\n"
        "\n"
        "1. **Which** 3 of the 7 legs reproduce.\n"
        "Read-only.\n"
    )
    out = _extract(body)
    assert "echo hello" in out, out
    for leaked in ("Three questions", "Which", "Read-only"):
        assert leaked not in out, (
            f"trailing prose {leaked!r} leaked into the command — the #9400 "
            f"recurrence of BL-20260731-TRAINERDIAG-TRAILING-PROSE:\n{out}")


def test_the_general_rule_does_not_break_an_indented_continuation():
    """A blank line INSIDE the block must not end it — only a dedent does."""
    body = (
        "cmd: |\n"
        "  first_command\n"
        "\n"
        "  second_command_after_a_blank_line\n"
        "\n"
        "Prose.\n"
    )
    out = _extract(body)
    assert "first_command" in out and "second_command_after_a_blank_line" in out, out
    assert "Prose." not in out, out
