"""The trainer-diag relay must not execute an issue body's PROSE.

BL-20260731-TRAINERDIAG-TRAILING-PROSE. The `cmd:` extractor stripped markdown
fence lines but never STOPPED at the closing one, so everything after the fenced
block — the explanatory paragraphs, the `---` rule, the attribution footer — was
handed to bash as commands. Observed live in trainer-diag issue #8157, whose own
output carried `Expected: command not found` after the real work had run.

Harmless that time. Not harmless in general: prose is untrusted-ish free text
that can contain backticks (command substitution), parentheses (a syntax error
that can abort the remainder), and redirects. A body that reads as documentation
must never execute as code.

These tests run the REAL awk program, extracted from the workflow YAML, rather
than a copy of it — a copy would let the workflow and its test drift apart,
which is the failure mode this repo's guards exist to catch.
"""
from __future__ import annotations

import re
import shutil
import subprocess
from pathlib import Path

import pytest

_WORKFLOW = (Path(__file__).resolve().parents[1]
             / ".github" / "workflows" / "trainer-vm-diag.yml")


def _awk_program() -> str:
    """Pull the extractor's awk source straight out of the workflow."""
    text = _WORKFLOW.read_text(encoding="utf-8")
    m = re.search(r"awk '\n(.*?)\n\s*' \)\"", text, re.DOTALL)
    assert m, "could not locate the awk program in trainer-vm-diag.yml"
    return m.group(1)


def _extract(body: str) -> str:
    awk = shutil.which("awk") or shutil.which("gawk") or shutil.which("mawk")
    if not awk:
        pytest.skip("awk not available")
    proc = subprocess.run([awk, _awk_program()], input=body,
                          capture_output=True, text=True, timeout=30)
    assert proc.returncode == 0, proc.stderr
    return proc.stdout


def test_trailing_prose_after_the_closing_fence_is_not_extracted():
    """The #8157 shape, verbatim in structure."""
    body = (
        "Applies the recovery, then verifies the write landed.\n"
        "\n"
        "```\n"
        "cmd:\n"
        "echo real-work\n"
        "```\n"
        "\n"
        "Expected from the dry run: **17 derived**, `vol_threshold_source` set.\n"
        "\n"
        "---\n"
        "_Generated by [Claude Code](https://claude.ai/code)_\n"
    )
    out = _extract(body)
    assert "echo real-work" in out
    assert "Expected from the dry run" not in out, (
        "trailing prose leaked into the command — this is the #8157 defect")
    assert "Generated by" not in out
    assert "---" not in out


def test_backticks_in_trailing_prose_never_reach_the_command():
    """Command substitution is the sharp edge, not the noise."""
    body = (
        "```\n"
        "cmd:\n"
        "echo safe\n"
        "```\n"
        "Note: `rm -rf /tmp/whatever` would be substituted if this leaked.\n"
    )
    out = _extract(body)
    assert "echo safe" in out
    assert "rm -rf" not in out


def test_cmd_that_opens_its_own_fence_still_works():
    """The other documented layout: `cmd:` first, fence second."""
    body = (
        "cmd:\n"
        "```bash\n"
        "echo one\n"
        "echo two\n"
        "```\n"
        "trailing prose here\n"
    )
    out = _extract(body)
    assert "echo one" in out and "echo two" in out
    assert "trailing prose" not in out
    assert "```" not in out


def test_unfenced_single_line_cmd_is_unchanged():
    body = "cmd: journalctl -u ict-trainer.service -n 100\n"
    assert _extract(body).strip() == "journalctl -u ict-trainer.service -n 100"


def test_unfenced_block_still_stops_at_the_next_top_level_key():
    """BL-20260607-002 behaviour must survive the fence change."""
    body = (
        "cmd: |\n"
        "  echo alpha\n"
        "  echo beta\n"
        "reason: |\n"
        "  some prose that must not run\n"
    )
    out = _extract(body)
    assert "echo alpha" in out and "echo beta" in out
    assert "some prose that must not run" not in out
    assert "reason:" not in out


def test_a_script_line_is_not_mistaken_for_a_top_level_key():
    """`echo x` and `python3 y` have no colon; a URL line does, mid-line."""
    body = (
        "```\n"
        "cmd:\n"
        "echo 'see https://example.com/x'\n"
        "python3 scripts/ml/thing.py --root out\n"
        "```\n"
    )
    out = _extract(body)
    assert "python3 scripts/ml/thing.py --root out" in out
    assert "example.com" in out


def test_multiple_fenced_blocks_only_the_cmd_one_is_taken():
    body = (
        "```\n"
        "not the command\n"
        "```\n"
        "\n"
        "```\n"
        "cmd:\n"
        "echo chosen\n"
        "```\n"
        "\n"
        "```\n"
        "echo definitely not\n"
        "```\n"
    )
    out = _extract(body)
    assert "echo chosen" in out
    assert "not the command" not in out
    assert "echo definitely not" not in out
