#!/usr/bin/env python3
# wiring: scripts/ci/check_session_brief.py (session-brief-guard) + manual --write
"""Render the SESSION BRIEF into ``CLAUDE.md`` — the only channel that reaches a session in time.

WHY THIS EXISTS
---------------
Operator, 2026-08-26: *"We can't rely on CI guards that only work as a mechanism
at merge. We need to have the work being done correctly from the get go instead
of building bad PRs and then only discovering once we're trying to merge them
that we didn't work correctly. It has to be something that will force Claude to
use it at the very beginning of every session."*

The three channels, measured rather than assumed:

* **Hooks — DO NOT RUN HERE.** `.claude/settings.json` defines a SessionStart
  contract; its output was **absent from this session's context** on 2026-08-26,
  and the repo already records `1,379 consecutive "Found 0 total hooks in
  registry" log lines` (2026-08-20) for Claude Code on the web. A mechanism
  built on hooks is not merely weak, it is INVISIBLE — it looks installed and
  does nothing.
* **CI guards — fire at MERGE.** Correct as a backstop, useless as a way to make
  the work right in the first place. By the time they fail, the wrong work is
  already built.
* **`CLAUDE.md` — injected verbatim, before the first tool call**, under
  "These instructions OVERRIDE any default behavior". This is the only one that
  arrives in time.

So the brief's *content* goes INTO `CLAUDE.md`, not a pointer to a file a
session may or may not open. A pointer is exactly the step that gets skipped.

WHAT GOES IN, AND WHAT DOES NOT
-------------------------------
Only what is **DUE or UNPREVENTED**:

* `monitoring` items past their `check_every_days` cadence.
* recurrence classes whose `prevention` is still null.

Everything else is deliberately excluded. The brief must SHRINK as work lands —
a section that only grows is one more wall of text to skim past, which is the
failure mode of the thing it replaces. An empty brief renders as a single line
saying so, because "nothing is due" is itself information and a vanishing
section reads as a broken renderer.

⚠️ **This does not make anyone act.** It removes the excuse of not knowing, and
puts the item where the excuse cannot survive. That is a real and bounded claim:
do not describe it as enforcement.
"""
from __future__ import annotations

import argparse
import json
from datetime import date, datetime, timezone
from pathlib import Path

BEGIN = "<!-- SESSION-BRIEF:BEGIN — generated by scripts/ops/render_session_brief.py; do not hand-edit -->"
END = "<!-- SESSION-BRIEF:END -->"

_OPEN_ITEMS = Path("docs/claude/OPEN-ITEMS.json")
_RECURRENCE = Path("docs/claude/RECURRENCE-LEDGER.json")
_CLAUDE_MD = Path("CLAUDE.md")


def _load(p: Path) -> dict:
    try:
        return json.loads(p.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return {}


def _day(v) -> date | None:
    if not isinstance(v, str):
        return None
    for f in ("%Y-%m-%d", "%Y-%m-%dT%H:%M:%SZ"):
        try:
            return datetime.strptime(v.strip(), f).date()
        except ValueError:
            continue
    return None


def due_items(items: list, today: date) -> list:
    """Monitoring rows past their cadence. An UNDATEABLE row is DUE, never fresh."""
    out = []
    for it in items:
        if it.get("kind") != "monitoring":
            continue
        seen = _day(it.get("verified_at"))
        every = it.get("check_every_days")
        try:
            every = int(every)
        except (TypeError, ValueError):
            every = 0
        if seen is None or every <= 0 or (today - seen).days >= every:
            out.append(it)
    return out


def render(today: date | None = None) -> str:
    today = today or datetime.now(timezone.utc).date()
    oi = _load(_OPEN_ITEMS)
    rl = _load(_RECURRENCE)
    due = due_items(oi.get("items") or [], today)
    unprevented = [c for c in (rl.get("classes") or [])
                   if not c.get("prevention") and not c.get("unpreventable_because")]

    L = [BEGIN, ""]
    L.append("### ⚠️ SESSION BRIEF — what is DUE right now (generated; read before your first tool call)")
    L.append("")
    L.append("This block is rendered from `docs/claude/OPEN-ITEMS.json` + "
             "`docs/claude/RECURRENCE-LEDGER.json`. It is **inlined here rather than linked** "
             "because `CLAUDE.md` is the only surface that reaches a session before it acts — "
             "project **hooks do not run on Claude Code on the web** (verified 2026-08-26: the "
             "SessionStart contract's output was absent from the session context), and CI guards "
             "fire at merge, which is after the wrong work is already built. It lists only what is "
             "DUE or UNPREVENTED, so it shrinks as work lands.")
    L.append("")

    if due:
        L.append(f"**{len(due)} monitoring item(s) DUE — check and record what you OBSERVED:**")
        L.append("")
        for it in due:
            L.append(f"- **`{it['id']}`** — {it.get('summary','').strip()}")
            L.append(f"  - **Clears when:** {it.get('clears_when','(not stated)').strip()}")
            last = it.get("verified_at") or "never"
            L.append(f"  - Last observed: `{last}`. To clear for another cycle, set "
                     f"`verified_at` to today AND write what you saw into `observation` — "
                     f"a claim of progress is not an observation.")
        L.append("")
    else:
        L.append("**No monitoring item is due.** (The section is generated — an empty list here "
                 "means nothing is past its cadence, not that the renderer failed.)")
        L.append("")

    if unprevented:
        L.append(f"**{len(unprevented)} repeated mistake class(es) with NO executable prevention yet.** "
                 "These have each happened more than once. Reading them is not the point — if your "
                 "work touches one, the expectation is that you land the prevention or state why "
                 "none can exist:")
        L.append("")
        for c in unprevented:
            L.append(f"- **`{c['id']}`** ({c.get('occurrences','?')}× since {c.get('first_seen','?')}, "
                     f"last {c.get('last_seen','?')}) — {c.get('title','').strip()}")
            if c.get("why_it_recurs"):
                L.append(f"  - *Why it keeps happening:* {c['why_it_recurs'].strip()}")
        L.append("")
    else:
        L.append("**Every recorded repeated-mistake class has an executable prevention.**")
        L.append("")

    L.append(END)
    return "\n".join(L)


def current_block(text: str) -> str | None:
    if BEGIN not in text or END not in text:
        return None
    i = text.index(BEGIN)
    j = text.index(END) + len(END)
    return text[i:j]


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--write", action="store_true", help="update CLAUDE.md in place")
    ap.add_argument("--check", action="store_true", help="exit 1 if CLAUDE.md is stale")
    ap.add_argument("--self-test", action="store_true")
    a = ap.parse_args(argv)
    if a.self_test:
        return _self_test()

    want = render()
    text = _CLAUDE_MD.read_text(encoding="utf-8")
    have = current_block(text)

    if a.check:
        if have is None:
            print("::error::CLAUDE.md carries no SESSION-BRIEF block. It is the only surface that "
                  "reaches a session before its first tool call; without it the registers are "
                  "files nobody is made to open. Run: python3 scripts/ops/render_session_brief.py --write")
            return 1
        if have.strip() != want.strip():
            print("::error::CLAUDE.md's SESSION-BRIEF block is STALE vs the registers — a session "
                  "would read something that is no longer true, which is worse than reading nothing. "
                  "Run: python3 scripts/ops/render_session_brief.py --write")
            return 1
        print("session-brief: OK — CLAUDE.md matches the registers.")
        return 0

    if a.write:
        if have is None:
            print("no SESSION-BRIEF markers in CLAUDE.md — insert them first (see docs)")
            return 1
        _CLAUDE_MD.write_text(text.replace(have, want), encoding="utf-8")
        print("session-brief: CLAUDE.md updated.")
        return 0

    print(want)
    return 0


def _self_test() -> int:
    ok = True
    t = date(2026, 8, 26)
    fresh = {"kind": "monitoring", "id": "X", "summary": "s", "clears_when": "c",
             "verified_at": "2026-08-26", "check_every_days": 2}
    cases = [
        ("a freshly observed row is not due", due_items([fresh], t), False),
        ("a row past its cadence IS due",
         due_items([dict(fresh, verified_at="2026-08-01")], t), True),
        ("an UNDATEABLE row is due, never assumed fresh",
         due_items([dict(fresh, verified_at="whenever")], t), True),
        ("a never-observed row is due",
         due_items([{k: v for k, v in fresh.items() if k != "verified_at"}], t), True),
        ("a cadence of 0 means unchecked, so it is due",
         due_items([dict(fresh, check_every_days=0)], t), True),
        ("a non-monitoring row is never due",
         due_items([dict(fresh, kind="background_awareness", verified_at="2026-01-01")], t), False),
    ]
    for label, got, want in cases:
        good = bool(got) == want
        ok &= good
        print(f"  self-test ({label}): {'PASS' if good else 'FAIL'}")
    print("session-brief self-test:", "PASS" if ok else "FAIL")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
