#!/usr/bin/env python3
# wiring: scripts/ci/run_guards.py::session-brief-guard (--self-test, --check) + manual --write
"""Render the SESSION BRIEF into ``CLAUDE.md`` — the only channel that reaches a session in time.

WHY THIS EXISTS
---------------
Operator, 2026-08-26: *"We can't rely on CI guards that only work as a mechanism
at merge. We need to have the work being done correctly from the get go instead
of building bad PRs and then only discovering once we're trying to merge them
that we didn't work correctly. It has to be something that will force Claude to
use it at the very beginning of every session."*

The three channels, measured rather than assumed:

* **Hooks — DO NOT RUN HERE.** `.claude/settings.json` defines a SessionStart
  contract; its output was **absent from this session's context** on 2026-08-26,
  and the repo already records `1,379 consecutive "Found 0 total hooks in
  registry" log lines` (2026-08-20) for Claude Code on the web. A mechanism
  built on hooks is not merely weak, it is INVISIBLE — it looks installed and
  does nothing.
* **CI guards — fire at MERGE.** Correct as a backstop, useless as a way to make
  the work right in the first place. By the time they fail, the wrong work is
  already built.
* **`CLAUDE.md` — injected verbatim, before the first tool call**, under
  "These instructions OVERRIDE any default behavior". This is the only one that
  arrives in time.

So the brief's *content* goes INTO `CLAUDE.md`, not a pointer to a file a
session may or may not open. A pointer is exactly the step that gets skipped.

WHAT GOES IN, AND WHAT DOES NOT
-------------------------------
Only what is **DUE or UNPREVENTED**:

* `monitoring` items past their `check_every_days` cadence.
* recurrence classes whose `prevention` is still null.

Everything else is deliberately excluded. The brief must SHRINK as work lands —
a section that only grows is one more wall of text to skim past, which is the
failure mode of the thing it replaces. An empty brief renders as a single line
saying so, because "nothing is due" is itself information and a vanishing
section reads as a broken renderer.

⚠️ **This does not make anyone act.** It removes the excuse of not knowing, and
puts the item where the excuse cannot survive. That is a real and bounded claim:
do not describe it as enforcement.
"""
from __future__ import annotations

import argparse
import json
import subprocess
from datetime import date, datetime, timezone
from pathlib import Path

BEGIN = "<!-- SESSION-BRIEF:BEGIN — generated by scripts/ops/render_session_brief.py; do not hand-edit -->"
END = "<!-- SESSION-BRIEF:END -->"

_OPEN_ITEMS = Path("docs/claude/OPEN-ITEMS.json")
_RECURRENCE = Path("docs/claude/RECURRENCE-LEDGER.json")
_CYCLE_PRIORITY = Path("docs/claude/CYCLE-PRIORITY.json")
_CLAUDE_MD = Path("CLAUDE.md")


def _load(p: Path) -> dict:
    try:
        return json.loads(p.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return {}


def _day(v) -> date | None:
    if not isinstance(v, str):
        return None
    for f in ("%Y-%m-%d", "%Y-%m-%dT%H:%M:%SZ"):
        try:
            return datetime.strptime(v.strip(), f).date()
        except ValueError:
            continue
    return None


def due_items(items: list, today: date) -> list:
    """Monitoring rows past their cadence. An UNDATEABLE row is DUE, never fresh."""
    out = []
    for it in items:
        if it.get("kind") != "monitoring":
            continue
        seen = _day(it.get("verified_at"))
        every = it.get("check_every_days")
        try:
            every = int(every)
        except (TypeError, ValueError):
            every = 0
        if seen is None or every <= 0 or (today - seen).days >= every:
            out.append(it)
    return out


def priority_lines(priority: dict, today: date) -> list:
    """A3 — the cycle's priority, rendered so a session inherits it without being told.

    ⚠️ **AN ABSENT PRIORITY IS RENDERED, NOT SKIPPED.** "no priority is set" and
    "the renderer broke" must not look identical — that is the collapsed-state
    defect this repo has a CI guard for, and a vanishing section reads as a bug.

    Kept to a few lines on purpose. The brief must SHRINK as work lands; a
    priority block that grew into a manifesto would be one more wall to skim
    past, which is the failure mode of the thing this replaces.
    """
    cur = (priority or {}).get("current")
    if not isinstance(cur, dict) or not str(cur.get("priority") or "").strip():
        return ["**No cycle priority is set.** (Generated from "
                "`docs/claude/CYCLE-PRIORITY.json` — this line means the register "
                "carries no current priority, NOT that the renderer failed. If you "
                "are about to choose what to work on, there is nothing steering that "
                "choice and you should say so rather than inventing one.)", ""]

    L = [f"**🎯 THIS CYCLE'S PRIORITY — {cur.get('cycle_id', '(unnamed cycle)')}**", ""]
    L.append(f"> {str(cur['priority']).strip()}")
    L.append("")
    if str(cur.get("what_it_means_for_a_session") or "").strip():
        L.append(f"- **What that means for you:** {cur['what_it_means_for_a_session'].strip()}")

    set_by = cur.get("set_by") or "unknown"
    set_at = cur.get("set_at") or "unknown"
    basis = cur.get("basis") or "unstated"
    L.append(f"- Set by **{set_by}** on `{set_at}` · basis **{basis}** · "
             f"intent `{cur.get('intent_ref', '(none)')}`")

    review_by = _day(cur.get("review_by"))
    if review_by is None:
        L.append("- ⚠️ **No `review_by` date** — so nothing will ever mark this stale. "
                 "A priority that cannot expire is one nobody has to re-argue.")
    elif today > review_by:
        L.append(f"- ⚠️ **STALE — was due for review on `{review_by}`, "
                 f"{(today - review_by).days} day(s) ago.** It is still the last thing "
                 f"decided, which is why it is still shown; it is not evidence anyone "
                 f"currently holds it. Re-affirm or replace it in "
                 f"`docs/claude/CYCLE-PRIORITY.json`.")
    L.append("")
    return L


def render(today: date | None = None, *,
           open_items: dict | None = None,
           recurrence: dict | None = None,
           priority: dict | None = None) -> str:
    """Render the brief. Pass the registers explicitly to render a REF other than HEAD.

    `today` is threaded rather than read inside, because the diff-scoped check
    renders BOTH sides with the SAME date — that is what makes the clock term
    cancel (see `check_verdict`).
    """
    today = today or datetime.now(timezone.utc).date()
    oi = open_items if open_items is not None else _load(_OPEN_ITEMS)
    rl = recurrence if recurrence is not None else _load(_RECURRENCE)
    cp = priority if priority is not None else _load(_CYCLE_PRIORITY)
    due = due_items(oi.get("items") or [], today)
    unprevented = [c for c in (rl.get("classes") or [])
                   if not c.get("prevention") and not c.get("unpreventable_because")]

    L = [BEGIN, ""]
    L.append("### ⚠️ SESSION BRIEF — what is DUE right now (generated; read before your first tool call)")
    L.append("")
    L.append("This block is rendered from `docs/claude/CYCLE-PRIORITY.json` + "
             "`docs/claude/OPEN-ITEMS.json` + "
             "`docs/claude/RECURRENCE-LEDGER.json`. It is **inlined here rather than linked** "
             "because `CLAUDE.md` is the only surface that reaches a session before it acts — "
             "project **hooks do not run on Claude Code on the web** (verified 2026-08-26: the "
             "SessionStart contract's output was absent from the session context), and CI guards "
             "fire at merge, which is after the wrong work is already built. It lists only what is "
             "DUE or UNPREVENTED, so it shrinks as work lands.")
    L.append("")

    # A3 — the priority comes FIRST. A session reads top-down and stops early;
    # what steers the choice of work has to arrive before the list of work.
    L.extend(priority_lines(cp, today))

    if due:
        L.append(f"**{len(due)} monitoring item(s) DUE — check and record what you OBSERVED:**")
        L.append("")
        for it in due:
            L.append(f"- **`{it['id']}`** — {it.get('summary','').strip()}")
            L.append(f"  - **Clears when:** {it.get('clears_when','(not stated)').strip()}")
            last = it.get("verified_at") or "never"
            L.append(f"  - Last observed: `{last}`. To clear for another cycle, set "
                     f"`verified_at` to today AND write what you saw into `observation` — "
                     f"a claim of progress is not an observation.")
        L.append("")
    else:
        L.append("**No monitoring item is due.** (The section is generated — an empty list here "
                 "means nothing is past its cadence, not that the renderer failed.)")
        L.append("")

    if unprevented:
        L.append(f"**{len(unprevented)} repeated mistake class(es) with NO executable prevention yet.** "
                 "These have each happened more than once. Reading them is not the point — if your "
                 "work touches one, the expectation is that you land the prevention or state why "
                 "none can exist:")
        L.append("")
        for c in unprevented:
            L.append(f"- **`{c['id']}`** ({c.get('occurrences','?')}× since {c.get('first_seen','?')}, "
                     f"last {c.get('last_seen','?')}) — {c.get('title','').strip()}")
            if c.get("why_it_recurs"):
                L.append(f"  - *Why it keeps happening:* {c['why_it_recurs'].strip()}")
        L.append("")
    else:
        L.append("**Every recorded repeated-mistake class has an executable prevention.**")
        L.append("")

    L.append(END)
    return "\n".join(L)


def current_block(text: str) -> str | None:
    if BEGIN not in text or END not in text:
        return None
    i = text.index(BEGIN)
    j = text.index(END) + len(END)
    return text[i:j]


#: What a `--check` run concluded. Never collapsed: "the brief is stale" and
#: "THIS DIFF made it stale" are different facts, and only the second is this
#: PR's to fix.
VERDICTS = ("clean", "inherited", "introduced_registers_changed",
            "introduced_block_edited", "no_block", "base_unreadable")
_FAILING = ("introduced_registers_changed", "introduced_block_edited",
            "no_block", "base_unreadable")


def _git_show(ref: str, path: str) -> str | None:
    """The file's content at `ref`, or None if we could not read it.

    None is *we could not look*, never *it is absent* — the caller grades that
    as `base_unreadable` and FAILS, preserving the pre-diff-scoping behaviour
    rather than silently disabling the guard on a git glitch.
    """
    try:
        out = subprocess.run(["git", "show", f"{ref}:{path}"],
                             capture_output=True, text=True, timeout=30)
    except (OSError, subprocess.SubprocessError):
        return None
    return out.stdout if out.returncode == 0 else None


def check_verdict(*, want_head: str, have_head: str | None,
                  base_readable: bool,
                  want_base: str | None = None,
                  have_base: str | None = None) -> str:
    """Did THIS DIFF make the brief stale? A pure function, so it is arguable in tests.

    ⚠️ THE CLOCK IS WHY THIS EXISTS. `render()` calls `datetime.now()` and
    `due_items` flips a monitoring row to DUE once its cadence elapses — so the
    COMMITTED block in `CLAUDE.md` goes stale at a UTC-midnight boundary with no
    commit anywhere, and the whole-tree check then reds EVERY open PR until a
    human re-renders. A branch cut inside that window is stranded permanently,
    because nothing re-runs its checks.

    Measured 2026-08-31: `OI-20260826-MHG-OVER-COVER-MECHANISM-UNVERIFIED`
    (`verified_at 2026-08-29`, `check_every_days 2`) crossed into DUE at 00:00Z;
    the automation PRs opened at 00:47Z and 01:22Z both failed this guard on
    content they never touched, while `pytest-run` was green on both
    (`BL-20260830-A-TRANSIENT-RED-BASE-PERMANENTLY-STRANDS-AN-AUTOMERGE-BRANCH`).

    BOTH sides are rendered with the SAME `today`, so the time term is identical
    on each and cancels: the clock alone can never fail a PR. What survives is
    the register content and the committed block, which is exactly what a diff
    can change.

    ⚠️ `inherited` is NOT "the brief is fine" — it is "this PR did not break it".
    The caller prints it loudly and exits 0.
    """
    if have_head is None:
        return "no_block"
    if have_head.strip() == want_head.strip():
        return "clean"
    if not base_readable or want_base is None or have_base is None:
        return "base_unreadable"
    if want_head.strip() != want_base.strip():
        # The diff changed what the brief SHOULD say (it touched the registers),
        # so re-rendering is this author's job — and doing it also clears any
        # inherited drift. Without this branch a clock-stale base would let a
        # genuine register change through unrendered.
        return "introduced_registers_changed"
    if have_head.strip() != have_base.strip():
        return "introduced_block_edited"
    return "inherited"


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--write", action="store_true", help="update CLAUDE.md in place")
    ap.add_argument("--check", action="store_true", help="exit 1 if CLAUDE.md is stale")
    ap.add_argument("--base", default="",
                    help="diff-scope --check against this ref (e.g. origin/main): a "
                         "staleness that already exists on the base was not introduced "
                         "by this diff, so it is REPORTED rather than failed. Omit for "
                         "the strict whole-tree answer.")
    ap.add_argument("--self-test", action="store_true")
    a = ap.parse_args(argv)
    if a.self_test:
        return _self_test()

    want = render()
    text = _CLAUDE_MD.read_text(encoding="utf-8")
    have = current_block(text)

    if a.check:
        # Render BOTH sides with ONE date, so the clock term cancels.
        today = datetime.now(timezone.utc).date()
        want = render(today)
        want_base = have_base = None
        base_readable = False
        if a.base:
            oi_b = _git_show(a.base, str(_OPEN_ITEMS))
            rl_b = _git_show(a.base, str(_RECURRENCE))
            md_b = _git_show(a.base, str(_CLAUDE_MD))
            # ⚠️ The priority register MUST be read at the base too. If it fell
            # through to reading HEAD from disk, the priority term would be
            # identical on both sides and CANCEL — so changing the cycle priority
            # without re-rendering would grade `inherited` and pass, which is
            # exactly the drift this guard exists to catch. A register that is
            # newly rendered into the brief has to be newly diffed as well.
            # A base that predates this file reads as `{}` (absent, not
            # unreadable): the register did not exist there, which is a fact we
            # CAN establish, unlike a git failure.
            cp_b_raw = _git_show(a.base, str(_CYCLE_PRIORITY))
            if oi_b is not None and rl_b is not None and md_b is not None:
                try:
                    want_base = render(today, open_items=json.loads(oi_b),
                                       recurrence=json.loads(rl_b),
                                       priority=json.loads(cp_b_raw) if cp_b_raw else {})
                    have_base = current_block(md_b)
                    base_readable = have_base is not None
                except (ValueError, TypeError):
                    base_readable = False

        v = check_verdict(want_head=want, have_head=have,
                          base_readable=(base_readable if a.base else True),
                          want_base=want_base, have_base=have_base)

        if v == "clean":
            print("session-brief: OK — CLAUDE.md matches the registers.")
            return 0
        if v == "inherited":
            # ⚠️ NOT a clean bill of health. The brief IS stale; this diff did
            # not make it stale. Failing here strands a PR (often an automated
            # data commit with no author) for a clock tick it cannot control.
            print("::notice::session-brief: the brief is STALE, but the SAME staleness is "
                  f"already on {a.base} and this diff did not introduce it — reporting, not "
                  "failing. Whoever next touches the registers should run: "
                  "python3 scripts/ops/render_session_brief.py --write")
            print(f"session-brief: verdict=inherited (base={a.base})")
            return 0
        if v == "no_block":
            print("::error::CLAUDE.md carries no SESSION-BRIEF block. It is the only surface that "
                  "reaches a session before its first tool call; without it the registers are "
                  "files nobody is made to open. Run: python3 scripts/ops/render_session_brief.py --write")
            return 1
        if v == "base_unreadable":
            print(f"::error::session-brief: the block is STALE and {a.base or '<no base>'} could "
                  "NOT be read, so whether this diff introduced it is UNKNOWN — we did not look, "
                  "which is not the same as 'it was already broken'. Failing closed (the "
                  "pre-diff-scoping behaviour). Run: python3 scripts/ops/render_session_brief.py --write")
            return 1
        reason = ("this diff changes the registers, so re-rendering is part of it"
                  if v == "introduced_registers_changed"
                  else "this diff edits the SESSION-BRIEF block and it still does not match")
        print(f"::error::CLAUDE.md's SESSION-BRIEF block is STALE and THIS DIFF introduced it — "
              f"{reason}. A session would read something that is no longer true, which is worse "
              f"than reading nothing. Run: python3 scripts/ops/render_session_brief.py --write")
        print(f"session-brief: verdict={v} (base={a.base})")
        return 1

    if a.write:
        if have is None:
            print("no SESSION-BRIEF markers in CLAUDE.md — insert them first (see docs)")
            return 1
        _CLAUDE_MD.write_text(text.replace(have, want), encoding="utf-8")
        print("session-brief: CLAUDE.md updated.")
        return 0

    print(want)
    return 0


def _self_test() -> int:
    ok = True
    t = date(2026, 8, 26)
    fresh = {"kind": "monitoring", "id": "X", "summary": "s", "clears_when": "c",
             "verified_at": "2026-08-26", "check_every_days": 2}
    cases = [
        ("a freshly observed row is not due", due_items([fresh], t), False),
        ("a row past its cadence IS due",
         due_items([dict(fresh, verified_at="2026-08-01")], t), True),
        ("an UNDATEABLE row is due, never assumed fresh",
         due_items([dict(fresh, verified_at="whenever")], t), True),
        ("a never-observed row is due",
         due_items([{k: v for k, v in fresh.items() if k != "verified_at"}], t), True),
        ("a cadence of 0 means unchecked, so it is due",
         due_items([dict(fresh, check_every_days=0)], t), True),
        ("a non-monitoring row is never due",
         due_items([dict(fresh, kind="background_awareness", verified_at="2026-01-01")], t), False),
    ]
    for label, got, want in cases:
        good = bool(got) == want
        ok &= good
        print(f"  self-test ({label}): {'PASS' if good else 'FAIL'}")

    # --- A3: priority propagation -------------------------------------------
    pr = {"current": {"cycle_id": "CY-1", "priority": "Do the steering half.",
                      "what_it_means_for_a_session": "Prefer steering work.",
                      "set_by": "operator", "set_at": "2026-09-01",
                      "basis": "DECIDED", "intent_ref": "IN-1",
                      "review_by": "2026-09-08"}}
    pcases = [
        ("a set priority is rendered, with its cycle id",
         "CY-1" in "\n".join(priority_lines(pr, t)), True),
        ("the priority TEXT itself reaches the session",
         "Do the steering half." in "\n".join(priority_lines(pr, t)), True),
        ("who set it and on what basis are carried, not just the text",
         "operator" in "\n".join(priority_lines(pr, t))
         and "DECIDED" in "\n".join(priority_lines(pr, t)), True),
        ("AN ABSENT PRIORITY IS RENDERED, never silently skipped",
         "No cycle priority is set" in "\n".join(priority_lines({}, t)), True),
        ("a null current renders the same explicit absence",
         "No cycle priority is set" in "\n".join(priority_lines({"current": None}, t)), True),
        ("an empty priority STRING is an absence, not a blank quote",
         "No cycle priority is set" in "\n".join(
             priority_lines({"current": {"priority": "   "}}, t)), True),
        ("a priority past review_by is marked STALE, not dropped",
         "STALE" in "\n".join(priority_lines(pr, date(2026, 9, 20))), True),
        ("a STALE priority is still SHOWN — it is the last thing decided",
         "Do the steering half." in "\n".join(priority_lines(pr, date(2026, 9, 20))), True),
        ("a priority with no review_by is flagged as unable to expire",
         "cannot expire" in "\n".join(priority_lines(
             {"current": dict(pr["current"], review_by=None)}, t)).replace(
                 "never expire", "cannot expire")
         or "No `review_by`" in "\n".join(priority_lines(
             {"current": dict(pr["current"], review_by=None)}, t)), True),
        ("the priority reaches the RENDERED BRIEF, not just its helper",
         "CY-1" in render(t, open_items={}, recurrence={}, priority=pr), True),
        ("the brief renders the absence too",
         "No cycle priority is set" in render(t, open_items={}, recurrence={},
                                              priority={}), True),
    ]
    for label, got, want in pcases:
        good = got == want
        ok &= good
        print(f"  self-test (priority: {label}): {'PASS' if good else 'FAIL'}")

    # ⚠️ THE CANCELLATION TRAP. `--check` renders both sides with one date so the
    # CLOCK cancels. A register that is rendered but NOT read at the base would
    # cancel the same way — and a priority change would then pass unrendered,
    # which is the drift this guard exists to catch. This asserts the two sides
    # actually differ when only the priority differs.
    other = {"current": dict(pr["current"], priority="Something else entirely.")}
    a_side = render(t, open_items={}, recurrence={}, priority=pr)
    b_side = render(t, open_items={}, recurrence={}, priority=other)
    good = a_side != b_side
    ok &= good
    print("  self-test (priority: a priority-only change CHANGES the rendered brief, "
          f"so --check cannot cancel it away): {'PASS' if good else 'FAIL'}")
    good = check_verdict(want_head=b_side, have_head=a_side, base_readable=True,
                         want_base=a_side, have_base=a_side) == "introduced_registers_changed"
    ok &= good
    print("  self-test (priority: changing the priority without re-rendering is graded "
          f"INTRODUCED, not inherited): {'PASS' if good else 'FAIL'}")

    # The diff-scoping verdict. Stated as data so the policy is arguable here
    # rather than against a live PR.
    A, B = "brief-A", "brief-B"
    vcases = [
        ("head matches — clean",
         dict(want_head=A, have_head=A, base_readable=True, want_base=A, have_base=A),
         "clean"),
        ("THE CLOCK CASE: both sides stale identically, diff changed nothing",
         dict(want_head=B, have_head=A, base_readable=True, want_base=B, have_base=A),
         "inherited"),
        ("this diff changed the registers without re-rendering",
         dict(want_head=B, have_head=A, base_readable=True, want_base=A, have_base=A),
         "introduced_registers_changed"),
        ("this diff hand-edited the block and it still does not match",
         dict(want_head=A, have_head=B, base_readable=True, want_base=A, have_base=A),
         "introduced_block_edited"),
        ("no block at all",
         dict(want_head=A, have_head=None, base_readable=True, want_base=A, have_base=A),
         "no_block"),
        ("base unreadable — we did not look, so fail closed",
         dict(want_head=B, have_head=A, base_readable=False),
         "base_unreadable"),
    ]
    for label, kw, want in vcases:
        got = check_verdict(**kw)
        good = got == want
        ok &= good
        print(f"  self-test (verdict: {label}): {'PASS' if good else f'FAIL got={got}'}")

    print("session-brief self-test:", "PASS" if ok else "FAIL")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
