#!/usr/bin/env python3
# wiring: scripts/ci/run_guards.py::session-brief-guard (--self-test, --check) + manual --write
"""Render the SESSION BRIEF into ``CLAUDE.md`` — the only channel that reaches a session in time.

WHY THIS EXISTS
---------------
Operator, 2026-08-26: *"We can't rely on CI guards that only work as a mechanism
at merge. We need to have the work being done correctly from the get go instead
of building bad PRs and then only discovering once we're trying to merge them
that we didn't work correctly. It has to be something that will force Claude to
use it at the very beginning of every session."*

The three channels, measured rather than assumed:

* **Hooks — DO NOT RUN HERE.** `.claude/settings.json` defines a SessionStart
  contract; its output was **absent from this session's context** on 2026-08-26,
  and the repo already records `1,379 consecutive "Found 0 total hooks in
  registry" log lines` (2026-08-20) for Claude Code on the web. A mechanism
  built on hooks is not merely weak, it is INVISIBLE — it looks installed and
  does nothing.
* **CI guards — fire at MERGE.** Correct as a backstop, useless as a way to make
  the work right in the first place. By the time they fail, the wrong work is
  already built.
* **`CLAUDE.md` — injected verbatim, before the first tool call**, under
  "These instructions OVERRIDE any default behavior". This is the only one that
  arrives in time.

So the brief's *content* goes INTO `CLAUDE.md`, not a pointer to a file a
session may or may not open. A pointer is exactly the step that gets skipped.

WHAT GOES IN, AND WHAT DOES NOT
-------------------------------
Only what is **DUE or UNPREVENTED**:

* `monitoring` items past their `check_every_days` cadence.
* recurrence classes whose `prevention` is still null.

Everything else is deliberately excluded. The brief must SHRINK as work lands —
a section that only grows is one more wall of text to skim past, which is the
failure mode of the thing it replaces. An empty brief renders as a single line
saying so, because "nothing is due" is itself information and a vanishing
section reads as a broken renderer.

⚠️ **This does not make anyone act.** It removes the excuse of not knowing, and
puts the item where the excuse cannot survive. That is a real and bounded claim:
do not describe it as enforcement.
"""
from __future__ import annotations

import argparse
import json
import subprocess
import sys
from datetime import date, datetime, timezone
from pathlib import Path

BEGIN = "<!-- SESSION-BRIEF:BEGIN — generated by scripts/ops/render_session_brief.py; do not hand-edit -->"
END = "<!-- SESSION-BRIEF:END -->"

_OPEN_ITEMS = Path("docs/claude/OPEN-ITEMS.json")
_RECURRENCE = Path("docs/claude/RECURRENCE-LEDGER.json")
_CYCLE_PRIORITY = Path("docs/claude/CYCLE-PRIORITY.json")
_CONSTRAINT = Path("docs/claude/CONSTRAINT.json")
_SUNSET_ROOT = Path("comms/sunset")
_ROUTING = Path("docs/claude/work/CHECKLIST-ROUTING-AGE.json")
_CLAUDE_MD = Path("CLAUDE.md")


#: How one of the brief's source registers read. THREE STATES, NEVER COLLAPSED.
SRC_READ, SRC_ABSENT, SRC_UNREADABLE = "read", "absent", "unreadable"


def _read(p: Path) -> tuple[str, dict]:
    """`(state, doc)` for one source register.

    ⚠️ **THIS WAS ONE STATE UNTIL 2026-09-13 AND THE COLLAPSE LANDED ON THE ONE
    SURFACE THAT REACHES A SESSION BEFORE IT ACTS.** `_load` returned `{}` for a
    parse failure exactly as for a missing file, and every section downstream
    reads a missing key as *nothing to report*. MEASURED on `origin/main`
    @`7f832e8c0`: with `THIS IS NOT JSON` inserted into
    `docs/claude/OPEN-ITEMS.json`, the rendered brief went from **20 monitoring
    rows to 0**, exit 0, and printed

        **No monitoring item is due.** (The section is generated — an empty list
        here means nothing is past its cadence, not that the renderer failed.)

    — a sentence that is *itself* the falsehood, telling the reader in terms
    that an empty list is not a renderer failure at the exact moment it is. The
    rows that vanished include every `loud: true` row a session is obliged to
    report on, among them the real-money `alpaca_live` and prop-account items.

    ⚠️ `absent` IS NOT `unreadable`. A register that has never existed renders
    nothing and that is correct; one that has been CORRUPTED must say so.
    """
    try:
        raw = p.read_text(encoding="utf-8")
    except FileNotFoundError:
        return SRC_ABSENT, {}
    except OSError:
        return SRC_UNREADABLE, {}
    try:
        doc = json.loads(raw)
    except json.JSONDecodeError:
        return SRC_UNREADABLE, {}
    return (SRC_READ, doc) if isinstance(doc, dict) else (SRC_UNREADABLE, {})


def _load(p: Path) -> dict:
    """Doc only. Callers that need to know WHETHER they looked use `_read`."""
    return _read(p)[1]


def _latest_sunset_with_state() -> tuple[dict | None, list[str]]:
    """`(newest sunset index, paths that did not parse)`.

    ⚠️ **A CORRUPT NEWEST PASS USED TO RENDER THE PREVIOUS DAY'S AS CURRENT.**
    The loop takes the first truthy doc, and `_load` handed it `{}` for a parse
    failure, so it silently fell through to an older directory and the brief
    showed STALE candidates under today's heading — worse than showing none,
    because nothing said the reading was old.
    """
    bad: list[str] = []
    if not _SUNSET_ROOT.is_dir():
        return None, bad
    for day in sorted((p for p in _SUNSET_ROOT.iterdir() if p.is_dir()), reverse=True):
        idx = day / "INDEX.json"
        state, doc = _read(idx)
        if state == SRC_UNREADABLE:
            bad.append(str(idx))
            continue
        if doc:
            return doc, bad
    return None, bad


def _latest_sunset() -> dict | None:
    """The newest committed sunset pass, or ``None``.

    ⚠️ ``None`` is rendered as a line SAYING SO — it must never render as *no
    candidates*, which is the collapse `sunset_pass.render_brief_lines` exists
    to refuse one level down.
    """
    if not _SUNSET_ROOT.is_dir():
        return None
    for day in sorted((p for p in _SUNSET_ROOT.iterdir() if p.is_dir()), reverse=True):
        doc = _load(day / "INDEX.json")
        if doc:
            return doc
    return None


def _day(v) -> date | None:
    if not isinstance(v, str):
        return None
    for f in ("%Y-%m-%d", "%Y-%m-%dT%H:%M:%SZ"):
        try:
            return datetime.strptime(v.strip(), f).date()
        except ValueError:
            continue
    return None


def due_items(items: list, today: date) -> list:
    """Monitoring rows past their cadence. An UNDATEABLE row is DUE, never fresh."""
    out = []
    for it in items:
        if it.get("kind") != "monitoring":
            continue
        seen = _day(it.get("verified_at"))
        every = it.get("check_every_days")
        try:
            every = int(every)
        except (TypeError, ValueError):
            every = 0
        if seen is None or every <= 0 or (today - seen).days >= every:
            out.append(it)
    return out


def priority_lines(priority: dict, today: date) -> list:
    """A3 — the cycle's priority, rendered so a session inherits it without being told.

    ⚠️ **AN ABSENT PRIORITY IS RENDERED, NOT SKIPPED.** "no priority is set" and
    "the renderer broke" must not look identical — that is the collapsed-state
    defect this repo has a CI guard for, and a vanishing section reads as a bug.

    Kept to a few lines on purpose. The brief must SHRINK as work lands; a
    priority block that grew into a manifesto would be one more wall to skim
    past, which is the failure mode of the thing this replaces.
    """
    cur = (priority or {}).get("current")
    if not isinstance(cur, dict) or not str(cur.get("priority") or "").strip():
        return ["**No cycle priority is set.** (Generated from "
                "`docs/claude/CYCLE-PRIORITY.json` — this line means the register "
                "carries no current priority, NOT that the renderer failed. If you "
                "are about to choose what to work on, there is nothing steering that "
                "choice and you should say so rather than inventing one.)", ""]

    L = [f"**🎯 THIS CYCLE'S PRIORITY — {cur.get('cycle_id', '(unnamed cycle)')}**", ""]
    L.append(f"> {str(cur['priority']).strip()}")
    L.append("")
    if str(cur.get("what_it_means_for_a_session") or "").strip():
        L.append(f"- **What that means for you:** {cur['what_it_means_for_a_session'].strip()}")

    set_by = cur.get("set_by") or "unknown"
    set_at = cur.get("set_at") or "unknown"
    basis = cur.get("basis") or "unstated"
    L.append(f"- Set by **{set_by}** on `{set_at}` · basis **{basis}** · "
             f"intent `{cur.get('intent_ref', '(none)')}`")

    review_by = _day(cur.get("review_by"))
    if review_by is None:
        L.append("- ⚠️ **No `review_by` date** — so nothing will ever mark this stale. "
                 "A priority that cannot expire is one nobody has to re-argue.")
    elif today > review_by:
        L.append(f"- ⚠️ **STALE — was due for review on `{review_by}`, "
                 f"{(today - review_by).days} day(s) ago.** It is still the last thing "
                 f"decided, which is why it is still shown; it is not evidence anyone "
                 f"currently holds it. Re-affirm or replace it in "
                 f"`docs/claude/CYCLE-PRIORITY.json`.")
    L.append("")
    return L


def constraint_lines(constraint: dict) -> list:
    """A1 — the computed readout that sits BEHIND the priority (Phase D).

    Rendered immediately under A3's priority block, because the whole point of
    Phase D is that *"the cycle's priority has a computed readout behind it"* —
    a priority a session inherits with no diagnosis under it is still an
    assertion, however well-argued.

    ⚠️ **AN ABSENT READOUT IS RENDERED, NOT SKIPPED**, on the same reasoning
    ``priority_lines`` already applies: *nobody has generated one* and *the
    renderer broke* must not look identical.

    Delegates every word to ``constraint_readout.render_brief_lines`` so the
    brief and ``docs/claude/READOUT.md`` cannot drift into two answers about
    the same graph.
    """
    if not isinstance(constraint, dict) or not constraint.get("constraint"):
        return ["**No computed constraint readout is present.** (Generated from "
                "`docs/claude/CONSTRAINT.json` — this line means the file is absent or "
                "unreadable, NOT that nothing is blocked. Regenerate it with "
                "`python3 scripts/ops/constraint_readout.py --write`.)", ""]
    try:
        sys.path.insert(0, str(Path(__file__).resolve().parent))
        from constraint_readout import render_brief_lines  # type: ignore
        return render_brief_lines(constraint)
    except Exception as exc:  # noqa: BLE001
        return [f"**The constraint readout could not be rendered** "
                f"(`{type(exc).__name__}`). This is a RENDERER failure, not a finding "
                f"about the work store — do not read it as *nothing is blocked*.", ""]


def sunset_lines(sunset: dict | None) -> list:
    """E3 — the retirement candidates (Phase G).

    Rendered under the constraint readout, because it is the other half of the
    same question: the readout says where the chain is HELD UP, this says what
    should COME OUT. August ran 45 governance/hardening sprints against 2
    deployments, and complexity is monotonic by construction until something
    removes — so a session that reads only what is due keeps adding.

    ⚠️ **AN ABSENT PASS IS RENDERED, NOT SKIPPED**, on the same reasoning
    ``priority_lines`` and ``constraint_lines`` already apply: *nobody has run
    one* and *the renderer broke* must not look identical.

    Delegates every word to ``sunset_pass.render_brief_lines`` so the brief and
    ``comms/sunset/`` cannot drift into two answers about the same candidates.
    """
    try:
        sys.path.insert(0, str(Path(__file__).resolve().parent))
        from sunset_pass import render_brief_lines  # type: ignore
        return render_brief_lines(sunset)
    except Exception as exc:  # noqa: BLE001
        return [f"**The sunset pass could not be rendered** (`{type(exc).__name__}`). "
                f"This is a RENDERER failure, not a finding about the fleet — do not "
                f"read it as *nothing is a retirement candidate*.", ""]


def routing_lines(routing: dict | None) -> list:
    """MI-246 — the filed rows nobody has been given.

    Rendered HERE, above the monitoring list, because it is the one thing in the
    brief about work that has already been SCOPED and is going nowhere. The
    operator's mandate, 2026-09-10: *"ensure that things don't get dropped in
    the middle and that we actually finish things and execute them."*

    ⚠️ **AN ABSENT REGISTER IS RENDERED, NOT SKIPPED** — the same reasoning
    ``priority_lines`` / ``constraint_lines`` / ``sunset_lines`` already apply:
    *nobody computed it* and *nothing is stalled* must not look identical.

    Delegates every word to ``checklist_routing_age.render_brief_lines`` so the
    brief and the register cannot drift into two answers about the same rows.
    """
    try:
        sys.path.insert(0, str(Path(__file__).resolve().parent))
        from checklist_routing_age import render_brief_lines  # type: ignore
        return render_brief_lines(routing)
    except Exception as exc:  # noqa: BLE001
        return [f"**The unrouted-row reading could not be rendered** "
                f"(`{type(exc).__name__}`). This is a RENDERER failure, not a finding "
                f"about the checklist — do not read it as *nothing was left unrouted*.", ""]


def render(today: date | None = None, *,
           open_items: dict | None = None,
           recurrence: dict | None = None,
           priority: dict | None = None,
           constraint: dict | None = None,
           sunset: dict | None = None,
           routing: dict | None = None,
           unreadable_out: list[str] | None = None) -> str:
    """Render the brief. Pass the registers explicitly to render a REF other than HEAD.

    `today` is threaded rather than read inside, because the diff-scoped check
    renders BOTH sides with the SAME date — that is what makes the clock term
    cancel (see `check_verdict`).
    """
    today = today or datetime.now(timezone.utc).date()

    # ⚠️ WHICH SOURCES COULD NOT BE READ IS TRACKED, NOT DISCARDED. An explicitly
    # passed register is `read` by construction (the diff-scoped check supplies
    # both sides itself); only the ones loaded from disk here can fail.
    # ⚠️ AN OUT-PARAM, NOT A RE-READ IN `main`. A second list of "which files
    # are sources" would be a second definition, and the two drift the moment a
    # register is added — which is exactly how a newly rendered register ends up
    # unwatched. What `main` exits on is what `render` actually read.
    unreadable: list[str] = [] if unreadable_out is None else unreadable_out

    def _src(explicit: dict | None, path: Path) -> dict:
        if explicit is not None:
            return explicit
        state, doc = _read(path)
        if state == SRC_UNREADABLE:
            unreadable.append(str(path))
        return doc

    oi = _src(open_items, _OPEN_ITEMS)
    rl = _src(recurrence, _RECURRENCE)
    cp = _src(priority, _CYCLE_PRIORITY)
    cn = _src(constraint, _CONSTRAINT)
    rt = _src(routing, _ROUTING)
    if sunset is not None:
        sn = sunset
    else:
        sn, sunset_bad = _latest_sunset_with_state()
        unreadable.extend(sunset_bad)
    oi_unreadable = str(_OPEN_ITEMS) in unreadable
    due = due_items(oi.get("items") or [], today)
    unprevented = [c for c in (rl.get("classes") or [])
                   if not c.get("prevention") and not c.get("unpreventable_because")]

    L = [BEGIN, ""]
    L.append("### ⚠️ SESSION BRIEF — what is DUE right now (generated; read before your first tool call)")
    L.append("")
    L.append("This block is rendered from `docs/claude/CYCLE-PRIORITY.json` + "
             "`docs/claude/CONSTRAINT.json` + "
             "`comms/sunset/` + "
             "`docs/claude/work/CHECKLIST-ROUTING-AGE.json` + "
             "`docs/claude/OPEN-ITEMS.json` + "
             "`docs/claude/RECURRENCE-LEDGER.json`. It is **inlined here rather than linked** "
             "because `CLAUDE.md` is the only surface that reaches a session before it acts — "
             "project **hooks do not run on Claude Code on the web** (verified 2026-08-26: the "
             "SessionStart contract's output was absent from the session context), and CI guards "
             "fire at merge, which is after the wrong work is already built. It lists only what is "
             "DUE or UNPREVENTED, so it shrinks as work lands.")
    L.append("")

    # ⚠️ THE BANNER GOES FIRST, ABOVE EVERYTHING IT INVALIDATES. A session reads
    # top-down and stops early, and every section below renders a missing key as
    # "nothing to report" — so a source that could not be read has to be said
    # before the reader has drawn that conclusion, not after.
    if unreadable:
        L.append(f"🛑 **{len(unreadable)} OF THIS BRIEF'S SOURCE REGISTERS COULD NOT BE "
                 f"READ, so the sections below are INCOMPLETE — this is *we could not "
                 f"look*, NOT 'nothing is due'.** Every section here renders an absent "
                 f"key as nothing to report, so an unreadable source is silently "
                 f"indistinguishable from a quiet one unless it is named:")
        for rel in unreadable:
            L.append(f"  - `{rel}` — present but did NOT parse")
        L.append("")
        L.append("Restore it (`git checkout` the last parseable copy, or resolve the "
                 "conflict row-aware via `scripts/ops/merge_json_register.py`) and "
                 "re-render. Do NOT act on the list below as if it were complete.")
        L.append("")

    # A3 — the priority comes FIRST. A session reads top-down and stops early;
    # what steers the choice of work has to arrive before the list of work.
    L.extend(priority_lines(cp, today))

    # Phase D — the priority is an assertion until something computes the
    # readout under it. It goes HERE, between the priority and the due list,
    # because it is what a session should weigh the priority against.
    L.extend(constraint_lines(cn))

    # Phase G — the other half of the same question. The readout says where the
    # chain is held up; this says what should come out.
    L.extend(sunset_lines(sn))

    # MI-246 — a row that was FILED and never ROUTED. It goes above the
    # monitoring list because it is work already scoped and going nowhere,
    # which is cheaper to fix than anything below it.
    L.extend(routing_lines(rt))

    if due:
        L.append(f"**{len(due)} monitoring item(s) DUE — check and record what you OBSERVED:**")
        L.append("")
        for it in due:
            L.append(f"- **`{it['id']}`** — {it.get('summary','').strip()}")
            L.append(f"  - **Clears when:** {it.get('clears_when','(not stated)').strip()}")
            last = it.get("verified_at") or "never"
            L.append(f"  - Last observed: `{last}`. To clear for another cycle, set "
                     f"`verified_at` to today AND write what you saw into `observation` — "
                     f"a claim of progress is not an observation.")
        L.append("")
    elif oi_unreadable:
        # ⚠️ NEVER the reassurance below. That sentence says in terms that an
        # empty list is not a renderer failure, which is the one claim that is
        # false in exactly this case — and it is the claim a reader acts on.
        L.append("🛑 **MONITORING ITEMS: NOT LISTED — `docs/claude/OPEN-ITEMS.json` "
                 "could not be read.** This is NOT 'no monitoring item is due'. "
                 "Rows flagged `loud: true` are among the ones missing here, and a "
                 "session is obliged to report on those.")
        L.append("")
    else:
        L.append("**No monitoring item is due.** (The section is generated — an empty list here "
                 "means nothing is past its cadence, not that the renderer failed.)")
        L.append("")

    if unprevented:
        L.append(f"**{len(unprevented)} repeated mistake class(es) with NO executable prevention yet.** "
                 "These have each happened more than once. Reading them is not the point — if your "
                 "work touches one, the expectation is that you land the prevention or state why "
                 "none can exist:")
        L.append("")
        for c in unprevented:
            L.append(f"- **`{c['id']}`** ({c.get('occurrences','?')}× since {c.get('first_seen','?')}, "
                     f"last {c.get('last_seen','?')}) — {c.get('title','').strip()}")
            if c.get("why_it_recurs"):
                L.append(f"  - *Why it keeps happening:* {c['why_it_recurs'].strip()}")
        L.append("")
    else:
        L.append("**Every recorded repeated-mistake class has an executable prevention.**")
        L.append("")

    L.append(END)
    return "\n".join(L)


def current_block(text: str) -> str | None:
    if BEGIN not in text or END not in text:
        return None
    i = text.index(BEGIN)
    j = text.index(END) + len(END)
    return text[i:j]


#: What a `--check` run concluded. Never collapsed: "the brief is stale" and
#: "THIS DIFF made it stale" are different facts, and only the second is this
#: PR's to fix.
VERDICTS = ("clean", "inherited", "introduced_registers_changed",
            "introduced_block_edited", "no_block", "base_unreadable")
_FAILING = ("introduced_registers_changed", "introduced_block_edited",
            "no_block", "base_unreadable")


def _git_show(ref: str, path: str) -> str | None:
    """The file's content at `ref`, or None if we could not read it.

    None is *we could not look*, never *it is absent* — the caller grades that
    as `base_unreadable` and FAILS, preserving the pre-diff-scoping behaviour
    rather than silently disabling the guard on a git glitch.
    """
    try:
        out = subprocess.run(["git", "show", f"{ref}:{path}"],
                             capture_output=True, text=True, timeout=30)
    except (OSError, subprocess.SubprocessError):
        return None
    return out.stdout if out.returncode == 0 else None


BASE_MERGE_BASE = "merge_base"
BASE_TIP_UNRESOLVABLE = "tip_unresolvable"


def resolve_base(ref: str, *, head: str = "HEAD") -> tuple[str, str]:
    """Resolve *ref* to the FORK POINT, never to wherever the base is right now.

    Returns `(ref_to_read, state)` with two states that are never collapsed:
    `merge_base` (we found the fork point) and `tip_unresolvable` (**we could
    not look** -- unrelated histories, a shallow clone, no `HEAD`), which falls
    back to the tip.

    ⚠️ **THE FALLBACK IS TO THE TIP, NOT TO SKIPPING THE CHECK**, and the
    direction is deliberate: the tip is the pre-2026-09-12 behaviour, so an
    unresolvable base can only produce the FALSE FAILURE described below --
    never a false pass on a register change that really was unrendered. A
    recoverable red beats a silent green.

    === WHY THIS EXISTS (measured 2026-09-12, MI-280 U44) ===

    `check_verdict` asks "did THIS DIFF change the registers?" and answers it as
    `want_head != want_base`. That is only the diff's doing if `want_base` is
    the branch's ANCESTOR. Read at the base TIP it also differs when the base
    moved AHEAD -- which is the normal state of every working branch -- so the
    guard blamed the diff for a register the diff never touched.

    Reproduced against `origin/main` with two controls:

      * a branch at an older commit with a **ZERO-FILE diff** -> `::error:: ...
        THIS DIFF introduced it -- this diff changes the registers`, exit 1.
        There is no diff at all, so the stated cause cannot be true.
      * the same branch plus one unrelated test file, no register touched ->
        the identical error.

    ⚠️ **AND FOLLOWING THE PRINTED REMEDY MADE IT WORSE, WHICH IS WHY THIS IS A
    FIX AND NOT A REWORDING.** The message says to run `--write`. Measured, as
    CI sees it (the merge ref, i.e. the branch merged with main):

      * IGNORE the advice -> `verdict=inherited`, **exit 0, the PR passes**.
      * FOLLOW the advice -> `--write` bakes a brief rendered from the BRANCH's
        older registers; merging main then **CONFLICTS in `CLAUDE.md`**, and the
        guard grades `introduced_block_edited`, **exit 1**.

    So the guard talked an author out of a green PR and into a conflicted red
    one. That verdict is also what the constraint-readout cron dies on, per
    `BL-20260911-THE-CONSTRAINT-READOUT-CRON-NOW-CLEARS-ITS-SELF-TEST-AND-DIES-ON-SESSION-BRIEF-GUARD-REJECTING-THE-BRIEF-IT-JUST-RENDERED`.

    ⚠️ **THIS CHANGES NOTHING IN CI, BY CONSTRUCTION** -- do not read it as a
    loosening. GitHub runs `pull_request` checks on the MERGE REF, where `HEAD`
    already contains the base, so `merge-base(HEAD, base) == base` and both
    readings are the same ref. What it fixes is the LOCAL run, which is where a
    session meets this message and acts on it.
    """
    if not ref:
        return ref, BASE_TIP_UNRESOLVABLE
    try:
        out = subprocess.run(["git", "merge-base", head, ref],
                             capture_output=True, text=True, timeout=30)
    except (OSError, subprocess.SubprocessError):
        return ref, BASE_TIP_UNRESOLVABLE
    sha = out.stdout.strip()
    if out.returncode != 0 or not sha:
        return ref, BASE_TIP_UNRESOLVABLE
    return sha, BASE_MERGE_BASE


def check_verdict(*, want_head: str, have_head: str | None,
                  base_readable: bool,
                  want_base: str | None = None,
                  have_base: str | None = None) -> str:
    """Did THIS DIFF make the brief stale? A pure function, so it is arguable in tests.

    ⚠️ THE CLOCK IS WHY THIS EXISTS. `render()` calls `datetime.now()` and
    `due_items` flips a monitoring row to DUE once its cadence elapses — so the
    COMMITTED block in `CLAUDE.md` goes stale at a UTC-midnight boundary with no
    commit anywhere, and the whole-tree check then reds EVERY open PR until a
    human re-renders. A branch cut inside that window is stranded permanently,
    because nothing re-runs its checks.

    Measured 2026-08-31: `OI-20260826-MHG-OVER-COVER-MECHANISM-UNVERIFIED`
    (`verified_at 2026-08-29`, `check_every_days 2`) crossed into DUE at 00:00Z;
    the automation PRs opened at 00:47Z and 01:22Z both failed this guard on
    content they never touched, while `pytest-run` was green on both
    (`BL-20260830-A-TRANSIENT-RED-BASE-PERMANENTLY-STRANDS-AN-AUTOMERGE-BRANCH`).

    BOTH sides are rendered with the SAME `today`, so the time term is identical
    on each and cancels: the clock alone can never fail a PR. What survives is
    the register content and the committed block, which is exactly what a diff
    can change.

    ⚠️ `inherited` is NOT "the brief is fine" — it is "this PR did not break it".
    The caller prints it loudly and exits 0.
    """
    if have_head is None:
        return "no_block"
    if have_head.strip() == want_head.strip():
        return "clean"
    if not base_readable or want_base is None or have_base is None:
        return "base_unreadable"
    if want_head.strip() != want_base.strip():
        # The diff changed what the brief SHOULD say (it touched the registers),
        # so re-rendering is this author's job — and doing it also clears any
        # inherited drift. Without this branch a clock-stale base would let a
        # genuine register change through unrendered.
        return "introduced_registers_changed"
    if have_head.strip() != have_base.strip():
        return "introduced_block_edited"
    return "inherited"


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--write", action="store_true", help="update CLAUDE.md in place")
    ap.add_argument("--check", action="store_true", help="exit 1 if CLAUDE.md is stale")
    ap.add_argument("--base", default="",
                    help="diff-scope --check against this ref (e.g. origin/main): a "
                         "staleness that already exists on the base was not introduced "
                         "by this diff, so it is REPORTED rather than failed. Omit for "
                         "the strict whole-tree answer.")
    ap.add_argument("--self-test", action="store_true")
    a = ap.parse_args(argv)
    # The verdict below is about the COMMITTED tree. Say so when that is
    # not the tree you edited — BL-20260917-THE-DIRTY-TREE-NOTICE-LIVES-ONLY-IN-RUN-GUARDS.
    import pathlib  # noqa: PLC0415 — local, so importing this module stays free
    import sys as _sys  # noqa: PLC0415
    _sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1] / "ci"))
    import _dirty_tree  # noqa: E402,PLC0415 — path shim above
    _dirty_tree.warn()

    if a.self_test:
        return _self_test()

    unreadable: list[str] = []
    want = render(unreadable_out=unreadable)
    text = _CLAUDE_MD.read_text(encoding="utf-8")
    have = current_block(text)

    if unreadable:
        # ⚠️ LOUD *AND* NON-ZERO, AND THE BRIEF IS STILL WRITTEN. Writing it is
        # deliberate: the rendered block now carries the banner, so the session
        # that reads CLAUDE.md is TOLD. Refusing to write would leave the
        # previous brief in place, which asserts a completeness that is no
        # longer true and says nothing to anybody. The non-zero code is for the
        # producing workflow, which is the only party that can fix the file.
        print(f"::error::session-brief: {len(unreadable)} source register(s) are "
              "PRESENT and do NOT parse, so the rendered brief is INCOMPLETE. It "
              "carries a banner saying so; this exit code is for the workflow "
              "that produced it.")
        for rel in unreadable:
            print(f"  - {rel}")
        # ⚠️ `--check`'s OWN verdict is deliberately left alone. Its `inherited`
        # and `base_unreadable` branches exist to avoid stranding a PR for a
        # staleness it did not introduce, and a corrupt register on `main` is
        # not this diff's doing either. It is not a silent pass: the line above
        # prints on every path, and the rendered brief now carries a banner the
        # committed block does not, so the comparison reads STALE and exits 1
        # by the ordinary route. Changing that verdict would be a separate
        # decision about who gets stranded, taken without a measurement.

    if a.check:
        # Render BOTH sides with ONE date, so the clock term cancels.
        today = datetime.now(timezone.utc).date()
        want = render(today)
        want_base = have_base = None
        base_readable = False
        base_ref, base_state = resolve_base(a.base)
        if a.base:
            if base_state == BASE_TIP_UNRESOLVABLE:
                print("::notice::session-brief: could not resolve a merge-base for "
                      f"{a.base}; comparing against its TIP instead. That is *we could "
                      "not look*, not *they share no history* -- and it can mis-blame "
                      "this diff for a register the BASE moved. See resolve_base().")
            oi_b = _git_show(base_ref, str(_OPEN_ITEMS))
            rl_b = _git_show(base_ref, str(_RECURRENCE))
            md_b = _git_show(base_ref, str(_CLAUDE_MD))
            # ⚠️ The priority register MUST be read at the base too. If it fell
            # through to reading HEAD from disk, the priority term would be
            # identical on both sides and CANCEL — so changing the cycle priority
            # without re-rendering would grade `inherited` and pass, which is
            # exactly the drift this guard exists to catch. A register that is
            # newly rendered into the brief has to be newly diffed as well.
            # A base that predates this file reads as `{}` (absent, not
            # unreadable): the register did not exist there, which is a fact we
            # CAN establish, unlike a git failure.
            cp_b_raw = _git_show(base_ref, str(_CYCLE_PRIORITY))
            # Same argument for the routing register (MI-246): it IS rendered
            # into the brief, so it has to be diffed as well or a changed
            # reading would cancel on both sides and pass unrendered.
            rt_b_raw = _git_show(base_ref, str(_ROUTING))
            if oi_b is not None and rl_b is not None and md_b is not None:
                try:
                    want_base = render(today, open_items=json.loads(oi_b),
                                       recurrence=json.loads(rl_b),
                                       priority=json.loads(cp_b_raw) if cp_b_raw else {},
                                       routing=json.loads(rt_b_raw) if rt_b_raw else {})
                    have_base = current_block(md_b)
                    base_readable = have_base is not None
                except (ValueError, TypeError):
                    base_readable = False

        v = check_verdict(want_head=want, have_head=have,
                          base_readable=(base_readable if a.base else True),
                          want_base=want_base, have_base=have_base)

        if v == "clean":
            print("session-brief: OK — CLAUDE.md matches the registers.")
            return 0
        if v == "inherited":
            # ⚠️ NOT a clean bill of health. The brief IS stale; this diff did
            # not make it stale. Failing here strands a PR (often an automated
            # data commit with no author) for a clock tick it cannot control.
            print("::notice::session-brief: the brief is STALE, but the SAME staleness is "
                  f"already on {a.base} and this diff did not introduce it — reporting, not "
                  "failing. Whoever next touches the registers should run: "
                  "python3 scripts/ops/render_session_brief.py --write")
            print(f"session-brief: verdict=inherited (base={a.base})")
            return 0
        if v == "no_block":
            print("::error::CLAUDE.md carries no SESSION-BRIEF block. It is the only surface that "
                  "reaches a session before its first tool call; without it the registers are "
                  "files nobody is made to open. Run: python3 scripts/ops/render_session_brief.py --write")
            return 1
        if v == "base_unreadable":
            print(f"::error::session-brief: the block is STALE and {a.base or '<no base>'} could "
                  "NOT be read, so whether this diff introduced it is UNKNOWN — we did not look, "
                  "which is not the same as 'it was already broken'. Failing closed (the "
                  "pre-diff-scoping behaviour). Run: python3 scripts/ops/render_session_brief.py --write")
            return 1
        reason = ("this diff changes the registers, so re-rendering is part of it"
                  if v == "introduced_registers_changed"
                  else "this diff edits the SESSION-BRIEF block and it still does not match")
        print(f"::error::CLAUDE.md's SESSION-BRIEF block is STALE and THIS DIFF introduced it — "
              f"{reason}. A session would read something that is no longer true, which is worse "
              f"than reading nothing. Run: python3 scripts/ops/render_session_brief.py --write")
        print(f"session-brief: verdict={v} (base={a.base})")
        return 1

    if a.write:
        if have is None:
            print("no SESSION-BRIEF markers in CLAUDE.md — insert them first (see docs)")
            return 1
        _CLAUDE_MD.write_text(text.replace(have, want), encoding="utf-8")
        print("session-brief: CLAUDE.md updated.")
        return 2 if unreadable else 0

    print(want)
    return 2 if unreadable else 0


def _self_test() -> int:
    ok = True
    t = date(2026, 8, 26)
    fresh = {"kind": "monitoring", "id": "X", "summary": "s", "clears_when": "c",
             "verified_at": "2026-08-26", "check_every_days": 2}
    cases = [
        ("a freshly observed row is not due", due_items([fresh], t), False),
        ("a row past its cadence IS due",
         due_items([dict(fresh, verified_at="2026-08-01")], t), True),
        ("an UNDATEABLE row is due, never assumed fresh",
         due_items([dict(fresh, verified_at="whenever")], t), True),
        ("a never-observed row is due",
         due_items([{k: v for k, v in fresh.items() if k != "verified_at"}], t), True),
        ("a cadence of 0 means unchecked, so it is due",
         due_items([dict(fresh, check_every_days=0)], t), True),
        ("a non-monitoring row is never due",
         due_items([dict(fresh, kind="background_awareness", verified_at="2026-01-01")], t), False),
    ]
    for label, got, want in cases:
        good = bool(got) == want
        ok &= good
        print(f"  self-test ({label}): {'PASS' if good else 'FAIL'}")

    # --- A3: priority propagation -------------------------------------------
    pr = {"current": {"cycle_id": "CY-1", "priority": "Do the steering half.",
                      "what_it_means_for_a_session": "Prefer steering work.",
                      "set_by": "operator", "set_at": "2026-09-01",
                      "basis": "DECIDED", "intent_ref": "IN-1",
                      "review_by": "2026-09-08"}}
    pcases = [
        ("a set priority is rendered, with its cycle id",
         "CY-1" in "\n".join(priority_lines(pr, t)), True),
        ("the priority TEXT itself reaches the session",
         "Do the steering half." in "\n".join(priority_lines(pr, t)), True),
        ("who set it and on what basis are carried, not just the text",
         "operator" in "\n".join(priority_lines(pr, t))
         and "DECIDED" in "\n".join(priority_lines(pr, t)), True),
        ("AN ABSENT PRIORITY IS RENDERED, never silently skipped",
         "No cycle priority is set" in "\n".join(priority_lines({}, t)), True),
        ("a null current renders the same explicit absence",
         "No cycle priority is set" in "\n".join(priority_lines({"current": None}, t)), True),
        ("an empty priority STRING is an absence, not a blank quote",
         "No cycle priority is set" in "\n".join(
             priority_lines({"current": {"priority": "   "}}, t)), True),
        ("a priority past review_by is marked STALE, not dropped",
         "STALE" in "\n".join(priority_lines(pr, date(2026, 9, 20))), True),
        ("a STALE priority is still SHOWN — it is the last thing decided",
         "Do the steering half." in "\n".join(priority_lines(pr, date(2026, 9, 20))), True),
        ("a priority with no review_by is flagged as unable to expire",
         "cannot expire" in "\n".join(priority_lines(
             {"current": dict(pr["current"], review_by=None)}, t)).replace(
                 "never expire", "cannot expire")
         or "No `review_by`" in "\n".join(priority_lines(
             {"current": dict(pr["current"], review_by=None)}, t)), True),
        ("the priority reaches the RENDERED BRIEF, not just its helper",
         "CY-1" in render(t, open_items={}, recurrence={}, priority=pr), True),
        ("the brief renders the absence too",
         "No cycle priority is set" in render(t, open_items={}, recurrence={},
                                              priority={}), True),
    ]
    for label, got, want in pcases:
        good = got == want
        ok &= good
        print(f"  self-test (priority: {label}): {'PASS' if good else 'FAIL'}")

    # ⚠️ THE CANCELLATION TRAP. `--check` renders both sides with one date so the
    # CLOCK cancels. A register that is rendered but NOT read at the base would
    # cancel the same way — and a priority change would then pass unrendered,
    # which is the drift this guard exists to catch. This asserts the two sides
    # actually differ when only the priority differs.
    other = {"current": dict(pr["current"], priority="Something else entirely.")}
    a_side = render(t, open_items={}, recurrence={}, priority=pr)
    b_side = render(t, open_items={}, recurrence={}, priority=other)
    good = a_side != b_side
    ok &= good
    print("  self-test (priority: a priority-only change CHANGES the rendered brief, "
          f"so --check cannot cancel it away): {'PASS' if good else 'FAIL'}")
    # MI-246 — the SAME cancellation trap for the routing register. It is
    # rendered into the brief, so it must be diffed at the base too; these two
    # cases are what prove the base read above is load-bearing rather than
    # decorative.
    derived = {"schema_version": 1, "history_state": "derived", "threshold_hours": 24,
               "newly_stalled": [], "standing_count": 0, "within_count": 0,
               "ungradeable_count": 0}
    stalled = dict(derived, newly_stalled=[{
        "id": "MI-999", "title": "a filed row nobody was given", "owner": "unassigned",
        "status": "ready", "lane": "engineering", "tier": 1, "unrouted_hours": 31.0,
        "unrouted_since": "2026-09-10T00:00:00+00:00"}])
    r_a = render(t, open_items={}, recurrence={}, priority={}, routing=derived)
    r_b = render(t, open_items={}, recurrence={}, priority={}, routing=stalled)
    good = r_a != r_b and "MI-999" in r_b and "MI-999" not in r_a
    ok &= good
    print("  self-test (routing: a routing-only change CHANGES the rendered brief, "
          f"so --check cannot cancel it away): {'PASS' if good else 'FAIL'}")
    good = check_verdict(want_head=r_b, have_head=r_a, base_readable=True,
                         want_base=r_a, have_base=r_a) == "introduced_registers_changed"
    ok &= good
    print("  self-test (routing: a new unrouted crossing left unrendered is graded "
          f"INTRODUCED, not inherited): {'PASS' if good else 'FAIL'}")
    # ⚠️ An ABSENT register must render the absence, never nothing at all: a
    # vanishing section reads as an all-clear, which is the one reading MI-246
    # forbids.
    r_none = render(t, open_items={}, recurrence={}, priority={}, routing={})
    good = "NOT that nothing has been left unrouted" in r_none
    ok &= good
    print("  self-test (routing: an ABSENT register renders the absence, not an "
          f"all-clear): {'PASS' if good else 'FAIL'}")

    good = check_verdict(want_head=b_side, have_head=a_side, base_readable=True,
                         want_base=a_side, have_base=a_side) == "introduced_registers_changed"
    ok &= good
    print("  self-test (priority: changing the priority without re-rendering is graded "
          f"INTRODUCED, not inherited): {'PASS' if good else 'FAIL'}")

    # The diff-scoping verdict. Stated as data so the policy is arguable here
    # rather than against a live PR.
    A, B = "brief-A", "brief-B"
    vcases = [
        ("head matches — clean",
         dict(want_head=A, have_head=A, base_readable=True, want_base=A, have_base=A),
         "clean"),
        ("THE CLOCK CASE: both sides stale identically, diff changed nothing",
         dict(want_head=B, have_head=A, base_readable=True, want_base=B, have_base=A),
         "inherited"),
        ("this diff changed the registers without re-rendering",
         dict(want_head=B, have_head=A, base_readable=True, want_base=A, have_base=A),
         "introduced_registers_changed"),
        ("this diff hand-edited the block and it still does not match",
         dict(want_head=A, have_head=B, base_readable=True, want_base=A, have_base=A),
         "introduced_block_edited"),
        ("no block at all",
         dict(want_head=A, have_head=None, base_readable=True, want_base=A, have_base=A),
         "no_block"),
        ("base unreadable — we did not look, so fail closed",
         dict(want_head=B, have_head=A, base_readable=False),
         "base_unreadable"),
    ]
    for label, kw, want in vcases:
        got = check_verdict(**kw)
        good = got == want
        ok &= good
        print(f"  self-test (verdict: {label}): {'PASS' if good else f'FAIL got={got}'}")

    ok &= _self_test_resolve_base()
    ok &= _self_test_check_uses_merge_base()
    ok &= _self_test_unreadable_source()

    print("session-brief self-test:", "PASS" if ok else "FAIL")
    return 0 if ok else 1


def _self_test_unreadable_source() -> bool:
    """A source register that is PRESENT and does not PARSE must be SAID.

    MEASURED on `origin/main` @`7f832e8c0` before this existed: with
    `THIS IS NOT JSON` inserted into `docs/claude/OPEN-ITEMS.json` the brief
    rendered **0 monitoring rows instead of 20**, exit 0, and printed *"No
    monitoring item is due. (…an empty list here means nothing is past its
    cadence, not that the renderer failed.)"* — the reassurance being the
    falsehood. Same shape for `CYCLE-PRIORITY.json`: the priority section simply
    vanished.

    Both directions are asserted. A guard that only ever demonstrates its
    failures cannot show it is not simply always-red, and the over-refusal
    direction is real here: an EMPTY but valid register must keep rendering the
    reassurance, because then it IS true.
    """
    import os
    import shutil
    import tempfile

    ok = True
    rows = [{"kind": "monitoring", "id": "OI-X", "summary": "s",
             "clears_when": "c", "check_every_days": 1}]

    def _render(**kw) -> tuple[str, list[str]]:
        seen: list[str] = []
        return render(date(2026, 9, 13), unreadable_out=seen, **kw), seen

    # The renderer reads from CWD, so the controls need a tree of their own.
    cwd0 = os.getcwd()
    tmp = tempfile.mkdtemp(prefix="brief-src-")
    try:
        root = Path(tmp)
        (root / "docs/claude").mkdir(parents=True)
        os.chdir(root)

        # (1) corrupt -> named, and the reassurance is GONE.
        _OPEN_ITEMS.write_text("THIS IS NOT JSON")
        text, seen = _render()
        checks = [
            ("an unreadable OPEN-ITEMS is NAMED in the brief",
             str(_OPEN_ITEMS) in seen and "COULD NOT BE" in text, True),
            ("...and the 'nothing is past its cadence' reassurance is NOT printed",
             "No monitoring item is due" in text, False),
            ("...and the brief says the items are NOT LISTED",
             "MONITORING ITEMS: NOT LISTED" in text, True),
        ]

        # (2) POSITIVE CONTROL: valid and empty is a real reading, not a failure.
        _OPEN_ITEMS.write_text(json.dumps({"items": []}))
        text2, seen2 = _render()
        checks += [
            ("a VALID but EMPTY register is not reported unreadable", bool(seen2), False),
            ("...and it still renders the 'no monitoring item is due' line",
             "No monitoring item is due" in text2, True),
        ]

        # (3) POSITIVE CONTROL: a register with rows renders them, so the banner
        #     is not simply always-on.
        _OPEN_ITEMS.write_text(json.dumps({"items": rows}))
        text3, seen3 = _render()
        checks += [
            ("a register WITH a due row renders it and raises no banner",
             bool(seen3) is False and "OI-X" in text3, True),
        ]

        # (4) a NON-OPEN-ITEMS source fails independently — the banner is not
        #     wired to one register.
        _CYCLE_PRIORITY.write_text("{ NOT JSON")
        _, seen4 = _render()
        checks += [
            ("an unreadable CYCLE-PRIORITY is named too",
             str(_CYCLE_PRIORITY) in seen4, True),
        ]

        # (5) an ABSENT register is NOT unreadable — opposite facts.
        _CYCLE_PRIORITY.unlink()
        _OPEN_ITEMS.unlink()
        _, seen5 = _render()
        checks += [("an ABSENT register is not reported unreadable", bool(seen5), False)]

        for label, got, want in checks:
            good = got == want
            ok &= good
            print(f"  self-test (source: {label}): {'PASS' if good else 'FAIL'}")
    finally:
        os.chdir(cwd0)
        shutil.rmtree(tmp, ignore_errors=True)
    return ok


def _self_test_resolve_base() -> bool:
    """Does the base resolve to the FORK POINT, or to wherever the base is now?

    ⚠️ **THIS NEEDS A REAL REPOSITORY AND THAT IS THE WHOLE POINT.** The six
    `check_verdict` cases above are pure-function cases, and the defect this
    guards was invisible to every one of them: `check_verdict` was always
    correct GIVEN its inputs, and the caller fed it the base TIP. A pure test
    cannot see a plumbing bug, so this one builds a throwaway repo where the
    base MOVES -- the condition under which the wrong ref gives the wrong answer.

    The planted defect is the old behaviour itself: the test asserts that
    reading at the tip and reading at the fork point give DIFFERENT content, so
    a revert to `a.base` cannot leave this green.
    """
    import os
    import pathlib
    import shutil
    import tempfile

    if shutil.which("git") is None:
        # *We could not look*, never a pass. Distinguished from PASS on purpose:
        # a control that reports success when it could not run is how a guard
        # rots into decoration.
        print("  self-test (resolve_base): COULD-NOT-RUN -- no git on PATH")
        return False

    def run(*args, cwd):
        return subprocess.run(["git", *args], cwd=cwd, capture_output=True,
                              text=True, timeout=30)

    tmp = tempfile.mkdtemp(prefix="sbt-")
    try:
        run("init", "-q", "-b", "main", cwd=tmp)
        run("config", "user.email", "t@t", cwd=tmp)
        run("config", "user.name", "t", cwd=tmp)
        reg = pathlib.Path(tmp, "register.json")
        reg.write_text("R1\n", encoding="utf-8")
        run("add", "-A", cwd=tmp)
        run("commit", "-q", "-m", "base: register R1", cwd=tmp)
        fork = run("rev-parse", "HEAD", cwd=tmp).stdout.strip()

        run("checkout", "-q", "-b", "feature", cwd=tmp)
        pathlib.Path(tmp, "unrelated.txt").write_text("nothing to do with registers\n",
                                                      encoding="utf-8")
        run("add", "-A", cwd=tmp)
        run("commit", "-q", "-m", "feature: touches NO register", cwd=tmp)
        head = run("rev-parse", "HEAD", cwd=tmp).stdout.strip()

        # The base moves AHEAD, changing the register. The branch did not.
        run("checkout", "-q", "main", cwd=tmp)
        reg.write_text("R2\n", encoding="utf-8")
        run("add", "-A", cwd=tmp)
        run("commit", "-q", "-m", "base: register advanced to R2", cwd=tmp)
        tip = run("rev-parse", "HEAD", cwd=tmp).stdout.strip()
        run("checkout", "-q", "feature", cwd=tmp)

        cwd0 = os.getcwd()
        try:
            os.chdir(tmp)
            got_ref, got_state = resolve_base("main")
        finally:
            os.chdir(cwd0)

        checks = []
        checks.append(("state is merge_base", got_state == BASE_MERGE_BASE, got_state))
        checks.append(("resolves to the FORK POINT, not the tip",
                       got_ref == fork, f"{got_ref[:8]} (fork={fork[:8]} tip={tip[:8]})"))
        checks.append(("and the tip is genuinely a DIFFERENT commit -- "
                       "otherwise this control proves nothing",
                       fork != tip and head != tip, f"fork={fork[:8]} tip={tip[:8]}"))

        # THE PLANTED DEFECT: the old behaviour, asserted to give the WRONG
        # register content. If someone routes the reads back at `a.base`, the
        # branch's register reads R2 -- a change it never made -- and the guard
        # blames the diff. Pinning both readings here is what makes that revert
        # impossible to land quietly.
        at_fork = _git_show_in(tmp, got_ref, "register.json")
        at_tip = _git_show_in(tmp, "main", "register.json")
        checks.append(("reading at the fork point gives the branch's OWN register",
                       at_fork == "R1\n", repr(at_fork)))
        checks.append(("reading at the tip gives a register the branch never touched "
                       "(the defect, pinned)", at_tip == "R2\n", repr(at_tip)))

        # THE UNRESOLVABLE PATH, which the happy path above can never reach.
        # Without this, mislabelling `tip_unresolvable` as `merge_base` is a
        # one-word edit that no control sees -- measured: it escaped the first
        # draft of this battery.
        cwd1 = os.getcwd()
        try:
            os.chdir(tmp)
            bogus_ref, bogus_state = resolve_base("no-such-ref-anywhere")
            empty_ref, empty_state = resolve_base("")
        finally:
            os.chdir(cwd1)
        checks.append(("an unresolvable ref is tip_unresolvable, NOT merge_base",
                       bogus_state == BASE_TIP_UNRESOLVABLE, bogus_state))
        checks.append(("...and falls back to the ref itself, never to skipping",
                       bogus_ref == "no-such-ref-anywhere", bogus_ref))
        checks.append(("an empty base is tip_unresolvable too",
                       empty_state == BASE_TIP_UNRESOLVABLE, empty_state))

        # THE EXCEPT BRANCH. No git-based control can reach it -- it needs
        # subprocess itself to raise -- so it is driven directly. Without this,
        # mislabelling it `merge_base` is a one-word edit nothing sees, and the
        # case it covers (no git on PATH -> FileNotFoundError) is precisely when
        # a wrong label is most harmful.
        real_run = subprocess.run
        try:
            def _boom(*_a, **_k):
                raise OSError("planted: git could not be executed")
            subprocess.run = _boom
            raised_ref, raised_state = resolve_base("main")
        finally:
            subprocess.run = real_run
        checks.append(("a subprocess failure is tip_unresolvable, NOT merge_base",
                       raised_state == BASE_TIP_UNRESOLVABLE, raised_state))
        checks.append(("...and returns the ref unchanged", raised_ref == "main", raised_ref))

        good = True
        for label, passed, detail in checks:
            good &= passed
            print(f"  self-test (resolve_base: {label}): "
                  f"{'PASS' if passed else f'FAIL got={detail}'}")
        return good
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


def _self_test_check_uses_merge_base() -> bool:
    """END-TO-END: does `--check` actually READ at the fork point?

    ⚠️ **THIS EXISTS BECAUSE A PLANT ESCAPED.** The `resolve_base` control above
    tests the resolver in isolation, and routing `main()`'s five `_git_show`
    calls back at the base TIP -- which is the entire defect -- left that
    control GREEN. A resolver nothing is proven to USE is decoration, so this
    drives the real `main(["--check", "--base", "main"])` in a repo where the
    base moves, and the two readings give OPPOSITE exit codes.

    The repo is built so that `inherited` is the only correct answer: the base
    is ALREADY stale before the branch forks, so the branch inherits that
    staleness and changes no register of its own.
    """
    import os
    import pathlib
    import shutil
    import tempfile

    if shutil.which("git") is None:
        print("  self-test (check-uses-merge-base): COULD-NOT-RUN -- no git on PATH")
        return False

    def run(*args, cwd):
        return subprocess.run(["git", *args], cwd=cwd, capture_output=True,
                              text=True, timeout=30)

    def write_regs(root, oi, rl, cp, rt):
        pathlib.Path(root, "docs/claude/work").mkdir(parents=True, exist_ok=True)
        pathlib.Path(root, _OPEN_ITEMS).write_text(json.dumps(oi), encoding="utf-8")
        pathlib.Path(root, _RECURRENCE).write_text(json.dumps(rl), encoding="utf-8")
        pathlib.Path(root, _CYCLE_PRIORITY).write_text(json.dumps(cp), encoding="utf-8")
        pathlib.Path(root, _ROUTING).write_text(json.dumps(rt), encoding="utf-8")

    oi = json.loads(_OPEN_ITEMS.read_text(encoding="utf-8"))
    rl = json.loads(_RECURRENCE.read_text(encoding="utf-8"))
    cp = json.loads(_CYCLE_PRIORITY.read_text(encoding="utf-8")) if _CYCLE_PRIORITY.exists() else {}
    rt = json.loads(_ROUTING.read_text(encoding="utf-8")) if _ROUTING.exists() else {}
    items = oi["items"] if isinstance(oi, dict) and "items" in oi else oi

    # Pick a row the RENDERER actually reads. ⚠️ Not any row: an earlier draft
    # of this control mutated `title`, which reaches the brief for NO row, so
    # the needle was invisible and the control graded a fix that did not exist.
    today = date.today()
    base_block = render(today, open_items=oi, recurrence=rl, priority=cp, routing=rt)
    needle = None
    for it in items:
        if not isinstance(it, dict) or not isinstance(it.get("summary"), str):
            continue
        keep, it["summary"] = it["summary"], "NEEDLE-render-visible"
        if render(today, open_items=oi, recurrence=rl, priority=cp, routing=rt) != base_block:
            needle = it
            it["summary"] = keep
            break
        it["summary"] = keep
    if needle is None:
        print("  self-test (check-uses-merge-base): COULD-NOT-RUN -- no register row "
              "reaches the rendered brief, so no needle this control could plant")
        return False

    tmp = tempfile.mkdtemp(prefix="sbe2e-")
    cwd0 = os.getcwd()
    try:
        run("init", "-q", "-b", "main", cwd=tmp)
        run("config", "user.email", "t@t", cwd=tmp)
        run("config", "user.name", "t", cwd=tmp)

        # 1. base: registers R1, brief rendered from R1 -> consistent.
        write_regs(tmp, oi, rl, cp, rt)
        pathlib.Path(tmp, _CLAUDE_MD).write_text(
            f"# x\n\n{BEGIN}\n{base_block}\n{END}\n", encoding="utf-8")
        run("add", "-A", cwd=tmp)
        run("commit", "-q", "-m", "R1 + brief", cwd=tmp)

        # 2. base goes stale ON ITS OWN: register -> R2, brief NOT re-rendered.
        needle["summary"] = "NEEDLE-R2-inherited-staleness"
        write_regs(tmp, oi, rl, cp, rt)
        run("add", "-A", cwd=tmp)
        run("commit", "-q", "-m", "R2, brief NOT re-rendered", cwd=tmp)

        # 3. the branch forks HERE and touches no register at all.
        run("checkout", "-q", "-b", "feature", cwd=tmp)
        pathlib.Path(tmp, "unrelated.txt").write_text("no register here\n", encoding="utf-8")
        run("add", "-A", cwd=tmp)
        run("commit", "-q", "-m", "unrelated", cwd=tmp)

        # 4. the base moves AHEAD again, changing the register once more.
        run("checkout", "-q", "main", cwd=tmp)
        needle["summary"] = "NEEDLE-R3-base-moved-after-the-fork"
        write_regs(tmp, oi, rl, cp, rt)
        run("add", "-A", cwd=tmp)
        run("commit", "-q", "-m", "R3", cwd=tmp)
        run("checkout", "-q", "feature", cwd=tmp)

        # ⚠️ POSITIVE CONTROL FIRST: the repo must actually DISCRIMINATE. If the
        # needle does not move the rendered brief, `inherited` is the answer for
        # every reading and an rc of 0 would grade a fix that is not there --
        # measured: accepting an invisible needle escaped the first battery.
        fork_sha = run("merge-base", "HEAD", "main", cwd=tmp).stdout.strip()
        at_fork = _git_show_in(tmp, fork_sha, str(_OPEN_ITEMS))
        at_tip = _git_show_in(tmp, "main", str(_OPEN_ITEMS))
        if at_fork is None or at_tip is None:
            print("  self-test (check-uses-merge-base): COULD-NOT-RUN -- could not read "
                  "the register at the fork point and/or the tip")
            return False
        # ⚠️ DISCRIMINATE ON THE RENDERED BRIEF, NOT ON THE RAW REGISTER BYTES.
        # Comparing the JSON was the first attempt and it did NOT catch a plant
        # that accepted an invisible needle: the bytes differ whenever any field
        # is edited, while the guard only ever compares what `render()` EMITS.
        # A control must discriminate on the same quantity the code under test
        # reads, or it grades a condition nobody is in.
        try:
            brief_fork = render(today, open_items=json.loads(at_fork),
                                recurrence=rl, priority=cp, routing=rt)
            brief_tip = render(today, open_items=json.loads(at_tip),
                               recurrence=rl, priority=cp, routing=rt)
        except (ValueError, TypeError) as exc:
            print(f"  self-test (check-uses-merge-base): COULD-NOT-RUN -- {exc}")
            return False
        if brief_fork == brief_tip:
            print("  self-test (check-uses-merge-base): COULD-NOT-RUN -- the fork point "
                  "and the base tip RENDER THE SAME BRIEF, so this control cannot tell "
                  "the two readings apart and would pass for the wrong reason")
            return False

        os.chdir(tmp)
        rc = main(["--check", "--base", "main"])
        passed = rc == 0
        print("  self-test (check-uses-merge-base: a branch that touched NO register is "
              f"`inherited`, not blamed): {'PASS' if passed else f'FAIL rc={rc}'}")
        return passed
    finally:
        os.chdir(cwd0)
        shutil.rmtree(tmp, ignore_errors=True)


def _git_show_in(cwd: str, ref: str, path: str) -> str | None:
    """`git show ref:path` inside *cwd*. None is *we could not look*."""
    try:
        out = subprocess.run(["git", "show", f"{ref}:{path}"], cwd=cwd,
                             capture_output=True, text=True, timeout=30)
    except (OSError, subprocess.SubprocessError):
        return None
    return out.stdout if out.returncode == 0 else None


if __name__ == "__main__":
    raise SystemExit(main())
